- README.md
- config/100-namespace.yaml
- config/README.md
This should eventually include other things like a buildpack builder pipeline, clusterbuildtemplate for buildpack style builds, and standard configmaps.
> initial addition of config structure for ko

- docs/install.md
> fixes and simplifies install instructions using mini-broker

- pkg/kf/commands/root.go
Currently, the --built-in flag is only adhered to if it is the first
flag. This CL allows the flag to be anywhere in the command.
fixes #47
> ensure --built-in flag is adhered to

- pkg/kf/commands/apps/push.go
> Remove duplicated code

- pkg/kf/commands/apps/proxy.go
- pkg/kf/commands/apps/proxy_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
Moves proxy to use the apps client rather than list.
Passed integration tests locally.
> moved proxy to using apps client

- pkg/kf/buildpacks/client.go
- pkg/kf/buildpacks/fake/fake_client.go
- pkg/kf/commands/root.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
buildpacks.Client checks to ensure that the cluster has buildpacks.
fixes #99
> pkg/kf/buildpacks: Client implements doctor.Diagnosable

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/logs/tailer.go
Previously, when tailing logs wihtout following for an application that
didn't have a container (scaled to 0), it would block until it got a
log. This CL adds a 1 second timeout.
> pkg/kf/logs: time out for app without a container

- README.md
- docs/install.md
Updated the README and install instructions because they've been tailing the reality of the app. 
@juliaguo PTAL at the install instruction changes to see if they match up better with what you've experienced.
> updated readme and install instructions

- docs/development/README.md
- docs/development/crd-controllers.md
Added documentation around writing controllers based on my learnings from Knative.
We should be able to use this as a template for writing our own controller and fill in more details as questions arise.
> added controller docs

- hack/test.sh
> hack: ensure failure message is displayed

- pkg/kf/buildpacks/client.go
- pkg/kf/buildpacks/client_test.go
- pkg/kf/buildpacks/fake/fake_client.go
- pkg/kf/commands/buildpacks/stacks.go
- pkg/kf/commands/buildpacks/stacks_test.go
- pkg/kf/commands/root.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/testutil/integration.go
Stacks reads from the builder and displays the given stack.
fixes #157
> pkg/kf/commands/buildpacks: adds Stacks command

- config/300-space.yaml
- pkg/kf/commands/spaces/create.go
- pkg/kf/commands/spaces/create_test.go
- pkg/kf/commands/spaces/list.go
- pkg/kf/commands/spaces/list_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/spaces/client.go
- pkg/kf/spaces/client.yml
- pkg/kf/spaces/fake/fake_client.go
- pkg/kf/spaces/kfspace.go
- pkg/kf/spaces/kfspace_test.go
- pkg/kf/spaces/zz_generated.client.go
> moved spaces command to use kf.Space

- ci/concourse/pipelines/kf-pipeline.yml
Runs nightly to delete pipelines which have had their PRs closed/merged
> Add concourse cleanup job

- docs/spec/README.md
- docs/spec/app_push.md
- docs/spec/images/push.mmd
- docs/spec/images/push.svg
Added docs and swimlane for push flow.
> added docs for push

- go.mod
- go.sum
The fork removes an init function that is causing a panic in the
controllers.
related to #238
> all: use fork of github.com/knative/pkg

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/manifest/manifest.go
- pkg/kf/options.go
- pkg/kf/options.yml
- pkg/kf/push.go
[#8](https://github.com/poy/kf/issues/8)
> Support setting scale bounds

- pkg/kf/commands/root.go
- pkg/kf/commands/spaces/get.go
- pkg/kf/commands/spaces/get_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
> added space command

- pkg/apis/kf/v1alpha1/app_defaults.go
- pkg/apis/kf/v1alpha1/app_defaults_test.go
- pkg/apis/kf/v1alpha1/space_lifecycle_test.go
- pkg/apis/kf/v1alpha1/utils_test.go
> pkg/apis/kf/v1alpha1: add app defaults for empty containers

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_types.go
- pkg/apis/kf/v1alpha1/zz_generated.deepcopy.go
- pkg/reconciler/app/reconciler.go
These are some cherrypicked changes from the apps PR.
My intention is to get these in then write additional utilities to help finish up that PR as separate PRs and pull them in there to prevent its scope from getting any larger.
> patches to app lifecycle

- pkg/kf/buildpacks/client.go
- pkg/kf/buildpacks/client_test.go
- pkg/kf/buildpacks/fake/fake_client.go
- pkg/kf/commands/buildpacks/buildpacks.go
- pkg/kf/commands/buildpacks/buildpacks_test.go
- pkg/kf/commands/buildpacks/stacks.go
- pkg/kf/commands/buildpacks/stacks_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
> moved buildpacks and stacks to use the buildpack on a space

- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/scale_test.go
Before this CL, if flags weren't provided to the scale command it
failed. This CL will make the command instead fetch and display the
current scaling.
fixes #333
> pkg/kf/commands/apps: scale command without flags is a get

- docs/install.md
This CL removes an erroneous recommendation to do `kf marketplace`.
> Fix problem in install.md

- docs/developer-guide/README.md
- docs/developer-guide/configuring-routes.md
> started developer guide

- docs/install.md
- samples/apps/echo/go.mod
- samples/apps/helloworld/go.mod
- samples/apps/helloworld/go.sum
- samples/apps/helloworld/main.go
> docs: adds helloworld sample and references it

- cmd/kf/main.go
cobra Commands already print out errors
> Remove duplicate error message

- docs/developer-guide/README.md
update the README.md with [routes] to reference the linked document
> Update README.md with correct link

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
> pkg/kf/commands/apps: use unique space for each integration test

- pkg/kf/commands/apps/integration_test.go
This uses the echo app which is published to gcr.io/kf-releases/echo-app.
fixes #198
(note this this is waiting on #367)
> pkg/kg/commands/app: adds integration test for --docker-file

- samples/apps/multiple-apps/README.md
- samples/apps/multiple-apps/manifest.yml
This sample has a manifest that references two apps:
- echo
- helloworld
related to #381
> samples/apps: sample app manifest that deploys two apps

- pkg/kf/apps/zz_generated.client.go
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/internal/tools/clientgen/gentest/client_test.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/tmplfunctional.go
- pkg/kf/internal/tools/clientgen/tmplheader.go
- pkg/kf/routes/zz_generated.client.go
- pkg/kf/sources/zz_generated.client.go
- pkg/kf/spaces/zz_generated.client.go
This PR fixes #376 opening a path toward #353 and #196
> normalized diff for all clients

- go.mod
- pkg/apis/kf/v1alpha1/space_types.go
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
> add getters for space config

- .github/ISSUE_TEMPLATE/ask-question.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull-request-template.md
- SECURITY.md
> started issue templates

- docs/install.md
- pkg/kf/commands/install/kf/kf.go
> revert v0.7.0 knative build upgrade

- .github/ISSUE_TEMPLATE/proposal.md
Fixes # N/A
* Adds a new proposal issue template based on Google's project proposal template.
```release-note
```
> added proposal template

- docs/install.md
Fixes #
* Fixes the readme path for samples
*
*
```release-note
```
> Samples vs current sample

- pkg/kf/commands/install/kf/kf.go
fixes #493
*
*
*
```release-note
```
> pkg/kf/commands/install: ensure knative build installs first

- pkg/kf/commands/spaces/config_space_test.go
fixes #395
* adds unit test
*
*
```release-note
```
> pkg/kf/commands/spaces: adds test for number of args

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
Fixes #403 
*
*
*
```release-note
```
> Add unit test cases for app lifecycle

- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
Fixes a broken master where a field name changed causing tests to fail.
> fix broken master

- docs/kf.dev/content/en/docs/developers/reference-apps/awwvision/_index.md
This change adds the Awwvision sample app from service-broker-samples.
> Docs: Add Awwvision

- docs/kf.dev/content/en/docs/developers/env/_index.md
- docs/kf.dev/content/en/docs/developers/env/defaults/_index.md
Fixes #212 
* Add documentation for default env vars
*
*
Added documentation for default env vars.
> docs: Add default env var docs

- pkg/kf/commands/install/kf/kf.go
Fixes #
* Adds retry logic to install
*
*
```release-note
Fixed scenario where installer applies knative build CRD, but its not ready yet when kf CRDs are applied
```
> pkg/kf/commands/install/kf: add retry logic for kf

- docs/kf.dev/content/en/docs/getting-started/spring-music/_index.md
Fixes #553 
* VCAP_SERVICES is not automatically injected after a bind once a running app has been restarted.
> docs: correct service binding lifecycle in Spring Music

- cmd/webhook/main.go
Fixes #560
* Changes name of webhook to be kf specific
*
*
```release-note
Fixed webhook name
```
> cmd/webhook: changes webhook name to webhook.kf.dev

- pkg/kf/commands/install/kf/kf.go
Fixes #541
Fixes #473
* Installer waits for kf deployments to be ready
*
*
```release-note
Fixed race condition where space is created before webhook is ready
```
> pkg/kf/commands/install/kf: ensure deployments are ready

- go.mod
- go.sum
- pkg/kf/commands/apps/apps.go
- pkg/kf/commands/services/create-service.go
- pkg/kf/commands/services/helpers_test.go
- pkg/kf/commands/services/service.go
- pkg/kf/commands/services/service_test.go
- pkg/kf/commands/services/services.go
- pkg/kf/commands/services/services_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/describe/describe.go
- pkg/kf/describe/describe_test.go
- pkg/kf/services/fake/fake_client_interface.go
- pkg/kf/services/options.go
- pkg/kf/services/options.yml
- pkg/kf/services/services.go
- pkg/kf/services/services_test.go
- pkg/kf/services/utils.go
- pkg/kf/services/utils_test.go
Fixes #574
* Standardizes view of services
*
*
```release-note
Changed how services are displayed by CLI
```
> pkg/kf/commands/services: update views match cf

- docs/kf.dev/content/en/docs/developers/troubleshooting/_index.md
> docs: Add troubleshooting page for devs

- ci/concourse/pipelines/kf-pipeline.yml
- ci/concourse/pipelines/pr-pipeline.yml
Fixes #
* Use my own fork of the github pr resource to supply the kf pipeline with the PR's head url
* Set the git URI given the PR's head url
```release-note
```
> Attempt to fix concourse PR pipelines for forks

- ci/concourse/pipelines/pr-pipeline.yml
This should be read from credhub
> Fix ci_git_branch

- pkg/kf/logs/tailer.go
Fixes #
* Fixes log line using invalid `err`
* Exit loop if channel has been closed
*
```release-note
Fixed log line in `kf logs`
Fixed loop exit clause in `kf logs`
```
> pkg/kf/logs: fix warning message

- pkg/kf/commands/apps/apps.go
- pkg/kf/commands/apps/apps_test.go
Fixes #621
* Use Status to determine state
*
*
```release-note
Fixed bug where `kf apps` doesn't represent actual app status
```
> pkg/kf/commands/apps: use status to report app state

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_logs.md
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/apps/logs.go
Fixes #635
* Changed logs now tail/follow by default to match `cf logs`
```release-note
Changed logs now tail/follow by default to match `cf logs`
```
> fixes #635

- pkg/apis/kf/v1alpha1/app_defaults.go
Fixes #650
* Reduce default CPU request to 1/10th of a core
```release-note
```
> reduce default CPU

- pkg/kf/apps/push.go
Fixes #
none
* remove unused error
```release-note
Removed unused error code
```
> remove unused error

- docs/kf.dev/content/en/docs/developers/buildpacks/_index.md
- docs/kf.dev/content/en/docs/developers/buildpacks/go.md
- docs/kf.dev/content/en/docs/developers/buildpacks/java.md
- docs/kf.dev/content/en/docs/developers/buildpacks/node.md
> added docs for buildpacks

- docs/kf.dev/content/en/docs/developers/develop-and-manage-apps/kf-push/app-manifests/_index.md
Added application manifest documentation.
> added app manifest docs

- docs/kf.dev/content/en/docs/operators/administering-kf/setting-up-a-custom-domain.md
> added docs for domains

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
- pkg/kf/commands/apps/delete.go
- pkg/kf/commands/apps/restart.go
- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/set_env.go
- pkg/kf/commands/apps/set_env_test.go
- pkg/kf/commands/apps/start.go
- pkg/kf/commands/apps/stop.go
- pkg/kf/commands/apps/unset_env.go
- pkg/kf/commands/apps/unset_env_test.go
- pkg/kf/commands/routes/create_route.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/commands/service-bindings/unbind-service.go
- pkg/kf/commands/service-brokers/create-service-broker.go
- pkg/kf/commands/service-brokers/delete-service-broker.go
- pkg/kf/commands/services/create-service.go
- pkg/kf/commands/services/delete-service.go
- pkg/kf/commands/spaces/delete.go
- pkg/kf/commands/utils/utils.go
* Add message in async commands informing user that the command is asynchronous and work is being done to make it synchronous. #599 is a catch-all for adding synchronous capability to commands, individual commands will be linked as separate issues
> Add message in asynchronous commands

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
- docs/kf.dev/content/en/docs/operators/administering-kf/setting-up-a-custom-domain.md
- pkg/kf/commands/apps/delete.go
- pkg/kf/commands/apps/restart.go
- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/set_env.go
- pkg/kf/commands/apps/set_env_test.go
- pkg/kf/commands/apps/start.go
- pkg/kf/commands/apps/stop.go
- pkg/kf/commands/apps/unset_env.go
- pkg/kf/commands/apps/unset_env_test.go
- pkg/kf/commands/routes/create_route.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/commands/service-bindings/unbind-service.go
- pkg/kf/commands/service-brokers/create-service-broker.go
- pkg/kf/commands/service-brokers/delete-service-broker.go
- pkg/kf/commands/services/create-service.go
- pkg/kf/commands/services/delete-service.go
- pkg/kf/commands/spaces/delete.go
- pkg/kf/commands/utils/utils.go
Merge master into develop for git-flow based releasing
> Merge Master

- CHANGELOG.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-service-broker.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
- docs/kf.dev/content/en/docs/operators/administering-kf/setting-up-a-custom-domain.md
- pkg/kf/commands/apps/delete.go
- pkg/kf/commands/apps/restart.go
- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/set_env.go
- pkg/kf/commands/apps/set_env_test.go
- pkg/kf/commands/apps/start.go
- pkg/kf/commands/apps/stop.go
- pkg/kf/commands/apps/unset_env.go
- pkg/kf/commands/apps/unset_env_test.go
- pkg/kf/commands/routes/create_route.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/commands/service-bindings/integration_test.go
- pkg/kf/commands/service-bindings/unbind-service.go
- pkg/kf/commands/service-brokers/create-service-broker.go
- pkg/kf/commands/service-brokers/delete-service-broker.go
- pkg/kf/commands/services/create-service.go
- pkg/kf/commands/services/delete-service.go
- pkg/kf/commands/services/services.go
- pkg/kf/commands/spaces/delete.go
- pkg/kf/commands/utils/utils.go
- pkg/kf/services/services.go
> Release 010

- hack/build-release.sh
- hack/upload-release.sh
Fixes #674 
* Fixed release script to properly login and setup GOPATH
*
*
```release-note
Fixed release script to properly login and setup GOPATH
```
> hack: ensure GOPATH and auth when releasing

- docs/kf.dev/content/en/docs/developers/develop-and-manage-apps/kf-push/app-manifests/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_push.md
- pkg/apis/kf/v1alpha1/source_lifecycle.go
- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_test.go
- pkg/kf/sources/kfsource.go
- pkg/kf/sources/kfsource_test.go
- pkg/reconciler/source/resources/build.go
- pkg/reconciler/source/resources/build_test.go
- third_party/VENDOR-LICENSE
#656 
* Added ability to define stacks in manifests and the CLI
```release-note
Added ability to define stacks in manifests and the CLI.
```
> added the ability to select a stack

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/_index.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_proxy-route.md
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/apps/proxy.go
- pkg/kf/commands/root.go
- pkg/kf/commands/routes/integration_test.go
- pkg/kf/commands/routes/proxy_route.go
- pkg/kf/commands/routes/proxy_route_test.go
- pkg/kf/commands/utils/utils.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/testutil/integration.go
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
* Add `kf proxy-route` command and integration test
```release-note
Added kf proxy-route command
```
> Add kf proxy-route cmd

- hack/check-code-generator.sh
Looks like the last change caused all our new PRs to fail. Maybe due to bash vs sh differences.
> fix bash vs sh failure

- pkg/kf/apps/client.go
Fixes #727
* Ensure correct instance is being referenced
*
*
```release-note
```
> pkg/kf/apps: fix {Unb,B}indService funcs

- third_party/VENDOR-LICENSE
* Update `third_party/VENDOR-LICENSE`
> third_party: Update VENDOR-LICENSE

- pkg/kf/commands/service-bindings/vcap_services.go
Fixes #
*
*
*
```release-note
```
> Add vcap-services completion

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
1. Add retries to build step
2. Apply "on_failure" check at the job level instead of task level
3. Add license checking to nightly 'check' job
> Improve release pipeline

- hack/ko-apply.sh
Fixes #654 
* Create vendor directory in ko apply
* Create `GOPATH` entry in ko apply
```release-note
```
> fixed ko apply

- ci/concourse/pipelines/pr-pipeline.yml
Fixes #
* Check step gets 2h30m
*
*
```release-note
```
> ci/concourse/pipeline: check step needs more time

- pkg/kf/commands/install/gke/gke.go
- third_party/VENDOR-LICENSE
Fixes #486 #755 
* Added support for picking custom machine type during install.
```release-note
Added support for picking custom machine type during install.
```
> added support for selecting machine types

- ci/concourse/image/Dockerfile
Fixes #
* Update Google Cloud SDK
* Perform SHA256 check
```release-note
```
> Update Google Cloud SDK version in Concourse Image

- ci/concourse/pipelines/pr-pipeline.yml
Also added check-go-sum and check-vendor-license
> Split check step into multiple, aggregate steps

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/terraform/main.tf
This change introduces a single pipeline to handle tests (unit+integration) for all PRs.
> Feature: Single pipeline for PR tests

- ci/concourse/pipelines/pr-pipeline.yml
> fix pipeline

- pkg/reconciler/app/reconciler.go
Fixes #
* Fixes comment
*
*
```release-note
```
> pkg/reconciler/app: fix TODO comment

- pkg/reconciler/app/reconciler.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/space/reconciler.go
Fixes #791
* Log diffs in reconciler at Debug level
*
*
```release-note
Added debug logs to reconcilers to display diffs
```
> pkg/reconciler: log reconcile diffs

- pkg/apis/kf/v1alpha1/app_defaults.go
- pkg/apis/kf/v1alpha1/app_defaults_test.go
- pkg/kf/apps/health_check.go
- pkg/kf/apps/health_check_test.go
- pkg/kf/commands/apps/push_test.go
Fixes #772 
* Updates HealthCheck defaults to allow pushing to not fail
*
*
```release-note
Fixed mismatch in Knative Service defaults causing push to fail
```
> pkg/apis/kf/v1alpha1: update service defaults

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- pkg/kf/commands/install/gke/gke.go
Bump GKE versions to a version that contains a modern Cloud Run.
> bumped GKE versions

- pkg/apis/kf/v1alpha1/utils.go
- pkg/apis/kf/v1alpha1/utils_test.go
- pkg/kf/apps/log_tailer.go
Fixes various race conditions that we've been seeing for a while that are difficult to reproduce.
* Change handling of conflicts to update the status to unknown rather than failure because we know another change is going to be incoming but hasn't been reconciled yet.
* Update the resourceVersion on the log tailer in all successful conditions so we don't get duplicate messages for long-running pushes. 
```release-note
```
> fixes intermittent push failures

- ci/concourse/pipelines/pr-unipipeline.yml
- hack/README.md
- hack/create-gke-secret.sh
Fixes #
* Add script to ci. This allows #827 to work in the CI.
*
*
```release-note
```
> hack: adds create-gke-secret.sh

- hack/create-gke-secret.sh
Fixes #
* Fix ./hack/create-gke-secret.sh
*
*
```release-note
```
> hack: fix create-gke-secret

- hack/create-gke-secret.sh
Fixes #
* Fixes ./hack/create-gke-secret.sh ConfigMap name
*
*
```release-note
```
> hack: update create-gke-secret.sh push secret name

- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #
*
*
*
```release-note
```
> Update pr pipeline to always destroy terraform first

- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #
*
*
*
```release-note
```
> Concourse: don't wait for Terraform destroy

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- docs/install.md
- pkg/kf/commands/install/kf/kf.go
Fixes #
* update knative build version to v0.7.0
*
*
```release-note
Changed the version of knative-build to v0.7.0
```
> update knative build version to v0.7.0

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-service-broker.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_install_gke.md
- go.mod
- go.sum
- pkg/kf/cli/interactive_command.go
- pkg/kf/cli/interactive_command_test.go
- pkg/kf/cli/log.go
- pkg/kf/cli/prompts.go
- pkg/kf/commands/install/gke/gke.go
- pkg/kf/commands/install/kf/kf.go
- pkg/kf/commands/install/util/util.go
- pkg/kf/commands/service-bindings/integration_test.go
- pkg/kf/commands/service-brokers/delete-service-broker.go
- pkg/kf/commands/service-brokers/delete-service-broker_test.go
Fixes #547 
* Adds `cli` package with interactive features
* Adds `--interactive` flag to `kf install gke`
* Adds flags to `kf install gke` to allow it to be used in scripts
```release-note
Changed "kf install gke" to only be interactive when given --interactive flag
Added flags to "kf install gke" to allow it to be used in scripts
```
> pkg/kf/cli: adds interactive cli package

- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #
* use PR's hack dir in concourse pipeline
*
*
```release-note
```
> ci/concourse/pipelines: use PR's hack dir

- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #
* pipelines installs both Tekton and Knative Build
*
*
```release-note
```
> ci/concourse/pipelines: install both Tekton and Knative Build

- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #
* Add a manually step so we can clean up terraform environments to reduce quota usage.
This step can be expanded on in the future to also clean up the GKE infrastructure left behind.
```release-note
```
> Add reap concourse step

- pkg/kf/commands/apps/proxy.go
- pkg/kf/commands/routes/proxy_route.go
- pkg/kf/internal/utils/cli/utils.go
Change the proxy commands to not listen on ports if they're not going to start.
> fix listen failing unit tests

- third_party/service-catalog/manifests/catalog/templates/apiserver-deployment.yaml
- third_party/service-catalog/values/catalog.yml
Fixes #
* Bump memory requirements of service catalog to prevent OOM crashes
```release-note
```
> Bump service catalog memory requirements

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- pkg/kf/commands/install/gke/gke.go
Fixes #
* Change GKE version from 1.13.11-gke.9 to 1.13.11-gke.11
*
*
```release-note
Changed GKE version from 1.13.11-gke.9 to 1.13.11-gke.11
```
> pkg/kf/commands/install/gke: upgrade GKE version

- ci/concourse/pipelines/pr-unipipeline.yml
- hack/terraform-pre-destroy.sh
Terraform will destroy the network
> Fix error in terraform-pre-destroy.sh

- pkg/kf/doctor/cluster.go
Fixes #869 
* Added support for webhook checks in doctor
```release-note
Added support for webhook checks in `kf doctor`.
```
> doctor for mutating webhook

- ci/concourse/terraform/main.tf
WIP: update Terraform to match `kf install`
> updated stackdriver config

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-space.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unbind-service.md
- pkg/kf/commands/apps/delete.go
- pkg/kf/commands/routes/create_route.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/service-bindings/unbind-service.go
- pkg/kf/commands/service-bindings/unbind-service_test.go
- pkg/kf/commands/spaces/delete.go
- pkg/kf/internal/utils/cli/utils.go
Fixes #599 
* Update docs for commands that had been made synchronous. 
* Change unbind-service to be synchronous.
* Remove erroneous messages from create/delete-route.
```release-note
Changed `unbind-service` to be synchronous.
```
> finish removing async commands. Fixes #599

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
Fixes #884
* Fixed nightly pipeline
*
*
```release-note
Fixed nightly pipeline
```
> ci/concourse/pipelines: fix nightly pipelines

- hack/create-gke-secret.sh
Fixes #
* fix variable name in hack/create-gke-secret.sh
*
*
```release-note
```
> hack: fix variable name in create-gke-secret

- docs/apps/uaa/cloudsql-deployment.md
- docs/apps/uaa/main.tf
- docs/apps/uaa/output.tf
- docs/apps/uaa/vars.tf
* Changed UAA route in output.tf 
* Changed documentation describing building UAA from source
* Changed static value of target GCP project to variable
```release-note
Changed UAA route in output.tf 
Changed documentation describing building UAA from source
Changed static value of target GCP project to variable
```
> Improvements to UAA CloudSQL installation process

- README.md
Fixes # 907
*
*
*
```release-note
```
> update README.md to reflect archive status

- samples/apps/jsessionid-lb/README.md
- samples/apps/jsessionid-lb/go.mod
- samples/apps/jsessionid-lb/main.go
- samples/apps/session/README.md
- samples/apps/session/go.mod
- samples/apps/session/main.go
```release-note
Added example of JSESSIONID sticky load balancer.
```
> Added example load balancer application for JSESSIONID.

- samples/apps/jsessionid-lb/README.md
- samples/apps/jsessionid-lb/main.go
- samples/apps/jsessionid-lb/pkg/loadbalancer.go
- samples/apps/jsessionid-lb/pkg/loadbalancer_test.go
Added a section about how to profile the load balancer and tests to ensure it behaves correctly in the different failure scenarios..
> Added tests and load testing to the load balancer.

- .github/workflows/main.yml
Initial attempt at getting github-actions to run our Prow jobs
> Set up initial GitHub actions

- pkg/kf/commands/exporttok8s/exporttok8s_test.go
> Fix getContainer test

- docs/content/en/docs/v2.11/examples/deploying-docker-apps-with-nfs-mapfs.md
- pkg/reconciler/app/resources/deployment.go
- pkg/reconciler/app/resources/deployment_test.go
* Make Deployment use the container's existing entrypoint rather than a default one if the user has set one.
* Fix issue with duplicated args in NFS volumes.
* Add unit-tests for Deployment with NFS volumes. 
* Add instructions for using mapfs.
> Added a workaround to allow Docker containers to user mapfs.

- samples/README.md
- samples/apps/catsbroker/README.md
- samples/apps/echo/README.md
- samples/apps/envs/README.md
- samples/apps/jsessionid-lb/README.md
- samples/apps/multiple-apps/README.md
- samples/apps/service-broker/README.md
- samples/apps/session/README.md
- samples/apps/slowpoke/README.md
- samples/deployment-manager/README.md
Samples should only be used as examples and may not be production ready.
> Update samples with READMEs to indicate their scope.

- pkg/kf/commands/apps/set_env.go
These show how to set options that look like flags to cobra.
> Add examples to set-env

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- ci/cloudbuild/scripts/find_zone.py
- ci/cloudbuild/test.yaml
- ci/terraform/main.tf
- ci/terraform/variables.tf
- cmd/generate-release/scripts/create_dm_deployment.bash
- kf.code-workspace
* Local development
*  Configure [VS Code devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) for an improved local development experience. Devcontainer go version matches that used in the CI/CD pipelines.
* Improve CI/CD reliability
* Updated zone selection algorithm to order zones by available quota. In this way, the zone selected will always be the zone with the most available capacity. Separately bumped quota in us-east1 in our internal test project to ensure we have plenty of capacity there.
* Improved randomness of timeouts in tests -- cluster deployment workflows conflict when run concurrently. Added randomized timeouts to increase the likelihood of success upon multiple retries. 
* Fixed some improperly set defaults for our daily integration test workflows …
> Improve CI/CD reliability and local development workflows

- ci/cloudbuild/release-and-test.yaml
- ci/terraform/main.tf
- ci/terraform/variables.tf
- kf.code-workspace
* Add support for CI runs covering head as well as any tagged release versions
* Configure daily runs for head, current release, and the previous release version
> Configure coverage of head, current release, and previous release version

- docs/content/en/docs/v2.11/cli/generated/kf-configure-cluster-set-feature-flag.md
- docs/content/en/docs/v2.11/cli/generated/kf-configure-cluster-unset-feature-flag.md
- docs/content/en/docs/v2.11/cli/generated/kf-create-autoscaling-rule.md
- docs/content/en/docs/v2.11/cli/generated/kf-delete-autoscaling-rules.md
- docs/content/en/docs/v2.11/cli/generated/kf-disable-autoscaling.md
- docs/content/en/docs/v2.11/cli/generated/kf-enable-autoscaling.md
- docs/content/en/docs/v2.11/cli/generated/kf-map-route.md
- docs/content/en/docs/v2.11/cli/generated/kf-scale.md
- docs/content/en/docs/v2.11/cli/generated/kf-set-env.md
- docs/content/en/docs/v2.11/cli/generated/kf-unmap-route.md
- docs/content/en/docs/v2.11/cli/generated/kf-unset-env.md
- docs/content/en/docs/v2.11/cli/generated/kf-update-autoscaling-limits.md
Updates docs for Kf v2.11.17 release
> Update docs for Kf v2.11.17 release

- cmd/generate-release/cloudbuild.yaml
Patches our Tekton installer for compatibility with the latest version of ASM used in Kf's integration tests.
> Patch tekton YAML

- docs/content/en/docs/v2.11/developer/scaling/autoscaling.md
- docs/content/en/docs/v2.11/developer/scaling/manage-autoscaling.md
Kf supports K8s HPAs out of the box, but this wasn't apparent.
> Added HPA documentation to Kf.

- ci/cloudbuild/test.yaml
- Build image used for integration and acceptance steps used to use outdated gcloud CLI version
> Added gcloud upgrade to integration and acceptance tests

- .devcontainer/Dockerfile
- ci/cloudbuild/test.yaml
- ci/cloudbuild/unit-test.yaml
- cmd/generate-release/cloudbuild.yaml
```release-note
Changed go version to 1.23
```
> Update go to 1.23

- cmd/generate-release/scripts/install-asm.bash
- pkg/kf/commands/dependencies/dependencies.go
```release-note
Changed ASM version to 1.23.3
Changed Tekton version to 0.65.1
```
> Updated ASM to 1.23 and Tekton to 0.65.1

- pkg/kf/commands/dependencies/dependencies.go
* Upgrade Tekton
* Upgrade Config Connector
```release-note
* Upgrade Tekton
* Upgrade Config Connector
```
> Upgrade dependencies

- .github/workflows/update-docs.yml
- pkg/apis/kf/v1alpha1/zz_generated.conditions.appstatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.buildstatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.commonservicebrokerstatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.routestatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.serviceinstancebindingstatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.serviceinstancestatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.sourcepackagestatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.spacestatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.taskschedulestatus.go
- pkg/apis/kf/v1alpha1/zz_generated.conditions.taskstatus.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/zz_generated.client.go
- pkg/kf/builds/zz_generated.client.go
- pkg/kf/configmaps/zz_generated.client.go
- pkg/kf/internal/genericcli/zz_generated_options.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/logs/options.go
- pkg/kf/networkpolicies/zz_generated.client.go
- pkg/kf/routes/zz_generated.client.go
- pkg/kf/secrets/zz_generated.client.go
- pkg/kf/service-brokers/cluster/zz_generated.client.go
- pkg/kf/service-brokers/namespaced/zz_generated.client.go
- pkg/kf/serviceinstancebindings/zz_generated.client.go
- pkg/kf/serviceinstances/zz_generated.client.go
- pkg/kf/sourcepackages/zz_generated.client.go
- pkg/kf/spaces/zz_generated.client.go
- pkg/kf/tasks/zz_generated.client.go
- pkg/reconciler/apiservercerts/zz_generated.fakelister.apiservice_test.go
- pkg/reconciler/apiservercerts/zz_generated.fakelister.secret_test.go
Fixes #
* [Update upload-pages-artifact dependency as it was deprecated.](https://github.com/google/kf/pull/1083/commits/e396f11718b14c4429909a8b8c997b3554bcb8a1)
* [Changed year in the copyright text.](https://github.com/google/kf/pull/1083/commits/e6b14fe3221511f2188458d164cdfa936a1bca80)
```release-note
```
> Update upload-pages-artifact dependency as it was deprecated.

- .github/workflows/update-docs.yml
Fixes #
* updated deploy-pages version to v4
```release-note
```
> updated deploy-pages version to v4

- .devcontainer/Dockerfile
- ci/cloudbuild/test.yaml
- ci/cloudbuild/unit-test.yaml
- cmd/generate-release/cloudbuild.yaml
- cmd/generate-release/scripts/install-asm.bash
- pkg/kf/commands/dependencies/dependencies.go
Fixes #
* Updated go version to 1.24
* Update tekton to latest
* Update ASM to 1.25
```release-note
```
> Upgrade dep versions
