google/kf

- pkg/kf/service-bindings/client.go
- pkg/kf/service-bindings/client_test.go
- pkg/kf/service-bindings/vcap.go
- pkg/kf/service-bindings/vcap_test.go
Fixes #1
Our VCAP_SERVICES generator was missing functionality that would make services compatible with CF. Now we're most of the way there except for tags.
Most of this should go away once we build a webhook that injects VCAP_SERVICES into pods. That service will watch k8s resources and keep an internal cache so the values can be generated quickly leading to a different architecture.
> Fixed VCAP_SERVICES

- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
Push was failing because the registry wasn't being appended to the imagename so it was automaticlly being resolved to Docker Hub in the push command. Now we're adding it.
> fixed push not having a registry

- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
There is a regression where the push command no longer defaults an empty
path to the current working directory (CWD). This CL corrects it.
fixes #44
> push: fix bug by defaulting path to CWD

- pkg/kf/commands/apps/apps_test.go
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/buildpacks/buildpacks_test.go
- pkg/kf/internal/testutil/integration.go
- samples/apps/echo/README.md
- samples/apps/echo/go.mod
- samples/apps/echo/main.go
- samples/apps/envs/README.md
- samples/apps/envs/go.mod
- samples/apps/envs/main.go
- scripts/integration_tests.sh
part of #14
Adds end to end tests to cover the commands:
- push
- delete
- apps
- set-env
- unset-env
- env
- doctor
It adds the "envs" and "echo" sample Go apps. These apps are used by the
integration tests.
The integration tests are ran when the environment variable
GCP_PROJECT_ID is set while running the tests. If it is not set, they
will be skipped. They can also be skipped with the "--short" flag. The
tests run against a running knative cluster and assume GKE.
They are currently flaky due to https://github.com/poy/kf/issues/47
> all: adds apps end to end tests and sample apps

- samples/plugins/gke/cmd/push/integration_test.go
- samples/plugins/gke/tests.sh
This CL adds an integration test for the GKE's plugin push command.
> samples/plugins/gke: adds integration tests

- pkg/kf/internal/tools/clientgen/client.go
- pkg/kf/internal/tools/clientgen/common-options.yml
- pkg/kf/internal/tools/clientgen/genclient.go
- pkg/kf/internal/tools/clientgen/gentest/client.go
- pkg/kf/internal/tools/clientgen/gentest/client.yml
- pkg/kf/internal/tools/clientgen/gentest/client_test.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
- pkg/kf/internal/tools/clientgen/tmplclient.go
- pkg/kf/internal/tools/clientgen/tmplfunctional.go
- pkg/kf/internal/tools/clientgen/tmplheader.go
- pkg/kf/internal/tools/option-builder/option-builder.go
This PR creates a client generator for `kf` that we can use to create clients for specific CF concepts. It follows the Kubernetes model for handling extensions and provides a way to run mutations and filters before writes and reads.
This filtering and automatic application means we can map multiple CF concepts to the same Kubernetes object model, apply defaults, and enforce inavariants on the created objects.
An example client is included to test the autogenerator and auto-generated code.
> created client generator

- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_test.go
Only name and path fields currently implemented.
Required multiple apps per push to be supported.
> Initial manifest file support.

- pkg/kf/commands/wire_gen.go
- pkg/kf/deploy.go
- pkg/kf/deploy_test.go
- pkg/kf/push.go
- pkg/kf/push_test.go
Previously, the role of injecting environment variables was left to
push. This CL moves the injecting to the Deployer.
> pkg/kf: deployer injects env vars instead of push

- pkg/kf/commands/root.go
This CL prevents the help flag from displaying two sets of information
about the built-in flag. Previously, it would trigger the FlagSet that
is trying to decide if a built-in command should be used.
fixes #76
> pkg/kf/commands: fix usage display for built-in

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
This CL adds a test that uploads the sample buildpacks via
`upload-buildpacks` and then ensures they are listed via `buildpacks`.
It also stops running the integration tests in parallel. This is for two
reasons:
1. Flakyness. While we should eventually be able to run these tests in
parallel, it currently doesn't work well.
2. Uploading the buildpacks is required to run before the rest of the
tests. Therefore, we want to make sure those run first.
fixes #96
fixes #79
> pkg/kf/commands/apps: adds buildpack integration test

- pkg/kf/commands/apps/apps.go
- pkg/kf/commands/apps/apps_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
Integration tests pass locally. After this is merged the only
thing still using the AppLister will be deploy.go.
> Moved app listing to use the apps client.

- pkg/kf/fake/fake_log_tailer.go
- pkg/kf/log_tailer.go
- pkg/kf/log_tailer_test.go
- pkg/kf/push.go
- pkg/kf/push_test.go
This paves the way for a separate method that tails the logs of an
application instead of the logs that are egressed during deployment.
> pkg/kf: renames LogTailer.Tail to DeployLogs

- pkg/kf/commands/root.go
The "completion" command outputs to STDOUT the necessary script to add
bash auto-complete.
fixes #91
> adds "completion" command for bash auto-complete

- pkg/kf/apps/fake/fake_client.go
- pkg/kf/apps/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/gentest/client_test.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/tmplclient.go
- pkg/kf/spaces/fake/fake_client.go
- pkg/kf/spaces/zz_generated.client.go
This adds an upsert ability to generated clients. It does this by
listing the values on the cluster to see if any match the one with the
given name then merging and updating if that's the case otherwise
creating.
We can't use clever apimachinery functions to check error responses
because some of our upstream clients still use vendoring so the types
won't match.
There's also a bug fix for filtering based on labels and fieldselectors.
> Added the ability to upsert values.

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
Sub-context was being cancelled early, never allowing the json response to be read.
There might be better ways of handling the sub-context cancel.
Note that the manifest file is still not 100% guaranteed to be cleaned. This is due to various `t.Fatalf` calls throughout the integration test code.
> Fix manifest integration test

- pkg/kf/commands/apps/integration_test.go
Adds --built-in flag to manifest test. This is required if a plugin is
overriding the Push command.
> pkg/kf/commands/apps: fix manifest integration test

- docs/differences.md
- pkg/kf/builds/client.go
- pkg/kf/builds/client_test.go
- pkg/kf/builds/fake/fake_client.go
- pkg/kf/builds/options.go
- pkg/kf/builds/options.yml
- pkg/kf/builds/util.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/commands/utils/command_override_fetcher.go
- pkg/kf/commands/utils/command_override_fetcher_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/log_tailer.go
- pkg/kf/log_tailer_test.go
- pkg/kf/push.go
- pkg/kf/push_test.go
This PR is part of #111. It moves build tailing into the builds client and makes push use that before creating a Knative service.
> Push now builds before creating a Knative service.

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
The integration tests were still using the --built-in flag and therefore
were panicking. They also had a timing issue with the Env tests that now
use retries.
fixes #161
> pkg/kf/commands/apps: fix flaky/broken integration tests

- pkg/kf/apps/kfapp.go
- pkg/kf/apps/kfapp_test.go
- pkg/kf/deploy_test.go
- pkg/kf/push.go
This moves most of our direct accesses of child application properties into getters and setters prepping us to move to Knative 0.6 and eventually a custom CRD #111
> moved push to use getters/setters on kfapp

- pkg/kf/commands/apps/integration_test.go
The integration test that tests an application's environment variable's
value being overwritten has a tendency to be flaky. This CL skips this
part of the test until it is more reliable.
> pkg/kf/commands/apps: skips env overwrite test

- docs/install/Kf-with-CloudRun-on-GKE.md
The doc gives basic instructions for preparing a K8s cluster with Cloud
Run. It references the Cloud Run docs as well.
related to #148
> docs/install: adds docs for GKE+CR

- hack/upload-buildpacks-stack.sh
- hack/upload-buildpacks.sh
Previous this CL, the upload-buildpacks.sh script would use the
upload-buildpacks-stack.sh script without publishing the results. This
implied that if the latter script had never ran within that project,
then it would fail. Otherwise it would use an existing stack.
fixes #172
> hack: publish the stack when uploading buildpacks

- pkg/kf/commands/quotas/create.go
accidentally removed the line to set quota name, which causes creation to fail
> Fix create quota command

- pkg/kf/commands/quotas/create.go
- pkg/kf/commands/quotas/get.go
- pkg/kf/commands/quotas/list.go
- pkg/kf/commands/quotas/update_test.go
- pkg/kf/commands/quotas/utils.go
- pkg/kf/quotas/kfquota.go
reset a resource quota back to unlimited by passing in 0 for the desired resource in update command. (e.g. `kf update-quota test-quota -m 0` resets the memory quota to unlimited in `test-quota`)
> Reset resource quota to unlimited

- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/routes/delete_route_test.go
The encoded name did not match between create and delete.
> pkg/kf/commands/routes: fix bug in deleting route

- go.mod
- go.sum
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
This change updates to a version of Kontext that preserves file
permissions when creating an image. It also updates method signatures
where necessary to accomodate the ability to rebase introduced in this
version of Kontext. Where that is done, rebasing is disabled to preserve
existing behavior.
> go: use latest github.com/poy/kontext

- pkg/kf/log_tailer.go
- pkg/kf/log_tailer_test.go
- pkg/kf/push.go
This fixes slow pushes, the issue was that pushes would wait until the watcher timed out before. Now we check the `Ready` field of the service and note any condition there. This has the benefit of reducing duplicated messages at the end of the log.
I found an additional bug in push where the namespace wasn't passed along with the client so even if the build succeeded it could seem like it didn't.
Fixes #227 
Logs now look like this:
```
[deploy-revision] Starting app: test
[deploy-revision] Updated state to: Configuration "test" is waiting for a Revision to become ready.
[deploy-revision] Updated state to: Configuration "test" is waiting for a Revision to become ready.
[deploy-revision] Updated state to: Configuration "test" is waiting for a Revision to become ready.
[deploy-revision] …
```
> fix push being slow

- .travis.yml
- ci/concourse/pipelines/pr-pipeline.yml
- hack/check-code-generator.sh
Add a script to check if code-generator changes are committed.
This should help ensure `hack/update-codegen.sh` always succeeds on master.
> Add hack/check-code-generator

- pkg/kf/commands/config/config.go
Support loading kubeconfig from env `KUBECONFIG` if config kubeconfig is not set explicitly.
> support loading kubeconfig from env

- pkg/kf/commands/config/config.go
- pkg/kf/commands/config/config_test.go
Kubernetes has utilities for finding home dirs, use those rather than Hashicorp's
> use client-go's home rather than Hashicorp's

- cmd/webhook/main.go
- pkg/apis/kf/v1alpha1/app_types.go
- pkg/apis/kf/v1alpha1/app_types_test.go
- pkg/apis/kf/v1alpha1/app_validation.go
- pkg/apis/kf/v1alpha1/app_validation_test.go
This PR adds the ability to generate scaling annotations based on an app's `instances` field. The field also gets validation via webhook along with validation for the PodSpec.
> added app validation webhook and basic validation

- go.sum
A duplicate poy/kontext was introduced to go.sum recently. This change
removes that, leaving a single reference that points to the desired
version of the dependency.
> gomod: remove duplicates poy/kontext

- config/300-route.yaml
changes this:
```
$ kubectl get routes
NAME                   AGE
12061478071379941285   14h
```
to this:
```
$ kubectl get routes
NAME                   HOST   DOMAIN          PATH   APPS     AGE
12061478071379941285   test   kf.beesdb.com          [test]   15h
```
> added additional printer columns to routes

- docs/install.md
- hack/upload-buildpacks-stack.sh
- hack/upload-buildpacks.sh
Currently `gcr` is hardcoded as the container registry for buildpack uploads. This change intends to make it more generic. If user supplies their own container registry in `$KF_REGISTRY` then use that otherwise try defaulting to `gcr`(to preserve existing behaviour).
> Making registry settings more generic.

- pkg/kf/commands/root.go
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
- pkg/kf/commands/spaces/get.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
This command is intended to house all space configuration commands under a single root command `kf configure-space`.
CF's operator experience varies wildly when configuring the cluster or spaces seeming disjoint and it's unclear at any one point in time what can be configured on a space or the complete state. For example:
* enable-space-ssh - sets a specific feature flag
* disallow-space-ssh - sets a specific feature flag
* space-ssh-enabled - checks a specific feature flag
* running-environment-variable-group - gets list as a human friendly table
* staging-environment-variable-group - gets list as a human friendly table
* set-staging-environment-variable-group - set as a JSON object
* set-running-environment-variable-group - set as a JSON object
* feature-flags - gets a list of feature …
> added commands to manipulate space env vars

- pkg/kf/commands/apps/proxy.go
The Hostname field is no longer being populated in the latest version on knative
> fix proxy command

- pkg/apis/kf/v1alpha1/space_defaults.go
- pkg/apis/kf/v1alpha1/space_defaults_test.go
- pkg/apis/kf/v1alpha1/space_types.go
- pkg/apis/kf/v1alpha1/space_validation.go
- pkg/apis/kf/v1alpha1/space_validation_test.go
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
- pkg/kf/commands/spaces/create.go
- pkg/kf/commands/spaces/get.go
- pkg/kf/spaces/kfspace.go
- pkg/kf/spaces/kfspace_test.go
Adds defaulting and validation to spaces. They now require a container registry and buildpack builder. If no builder is supplied then the default one is chosen.
Additional info about what you can do with a space once it's created is now printed out.
> space defaulting and validation

- cmd/webhook/main.go
- pkg/apis/kf/v1alpha1/route_validation.go
- pkg/apis/kf/v1alpha1/route_validation_test.go
- pkg/apis/kf/v1alpha1/utils.go
- pkg/apis/kf/v1alpha1/utils_test.go
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/routes/create_route.go
- pkg/kf/commands/routes/create_route_test.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/commands/routes/delete_route_test.go
- pkg/kf/commands/routes/integration_test.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/map_route_test.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/commands/routes/unmap_route_test.go
- pkg/kf/testutil/integration.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
Routes are validated via a webhook that they have the proper fields:
- Name
- Namespace
- Spec.Domain
VirtualServices are also checked to ensure the hostname and domain
combination are available for that space.
> cmd/webhook: adds validation for v1alpha1.Route

- pkg/kf/builds/builtins.go
- pkg/kf/builds/options.go
- pkg/kf/builds/options.yml
- pkg/kf/builds/util.go
- pkg/kf/builds/util_test.go
- pkg/kf/push.go
This change provides environment variables (declared in an app manifest or as
arguments to `kf push`) to all steps in the build, allowing things like buildpack
configuration via environment variables.
Fixes #275
> kf/builds: provide env vars to build steps

- hack/build.sh
- hack/codegen-packages.txt
- hack/setup-codegen.sh
- hack/update-codegen.sh
`realpath` is not installed on OSX. Therefore the scripts were harder to
run for mac users.
fixes #297
> hack: remove any usage of `realpath`

- pkg/apis/kf/v1alpha1/source_lifecycle.go
- pkg/apis/kf/v1alpha1/source_lifecycle_test.go
- pkg/apis/kf/v1alpha1/source_types.go
This was preventing us from tailing logs given a source (no way to track back to a particular build).
> add build name to source status

- pkg/kf/commands/apps/proxy.go
- pkg/kf/commands/apps/proxy_test.go
This updates the proxy command to include examples of how to use `curl`:
```
Autodetecting app gateway. Specify a custom gateway using the --gateway flag.
Forwarding requests from 127.0.0.1:8080 to 35.192.224.169 with host echo.joseph.example.com
Example GET:
curl -H "Host: echo.joseph.example.com" http://35.192.224.169
Example POST:
curl --request POST -H "Host: echo.joseph.example.com" http://35.192.224.169 --data "POST data"
Browser link:
http://127.0.0.1:8080
NOTE: the first request may take some time if the app is scaled to zero
```
> added examples to proxy

- pkg/kf/apps/client.go
- pkg/kf/commands/apps/proxy.go
- pkg/kf/commands/apps/restart.go
- pkg/kf/commands/apps/restart_test.go
- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/buildpacks/buildpacks.go
- pkg/kf/commands/buildpacks/stacks.go
- pkg/kf/commands/root.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/kfapps/client.go
- pkg/kf/kfapps/fake/fake_client.go
- pkg/reconciler/app/resources/knativeservice.go
When a user does `kf restart`, kf will increment the
app.Spec.Template.UpdateRequests. The app controller will then update
the knative service, which will then result in a new revision.
fixes #286
> pkg/kf/commands/app: adds restart command

- pkg/kf/buildpacks/client.go
This PR sets docker registry authentication to anonymous while fetching the builder image. Since the builder image will be public there is no need for authentication.
The current mechanism also falls back to anonymous after attempting to authenticate, however requires `docker-credential-gcr` set in `$PATH`. This removes the need for having it. 
Also addresses https://github.com/google/kf/issues/322.
`kf buildpacks` should run fine without `docker-credential-gcr` set in `$PATH`.
> Using anonymous auth for fetching images

- pkg/kf/apps/client.go
- pkg/kf/apps/fake/fake_client.go
- pkg/kf/commands/apps/restage.go
- pkg/kf/commands/apps/restage_test.go
- pkg/kf/commands/root.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
When a user does `kf restage`, kf will increment the
app.Spec.Source.UpdateRequests. The app controller will then update the
knative build, which will then result in a new container and then
revision.
fixes #287
> pkg/kf/commands/app: adds restage command

- hack/upload-release.sh
- pkg/kf/commands/root.go
- pkg/kf/commands/version.go
version will display the current version. The version is provided via
ldflags. The hack/upload-release.sh script (used by the nightly build)
has been updated to include the current hash.
fixes #320
> pkg/kf/commands: adds version command

- pkg/kf/commands/apps/apps.go
- pkg/kf/commands/apps/apps_test.go
If there is an error connecting to the K8s cluster, showing the user
usage information is confusing.
> pkg/kf/commands/apps: apps command uses SilenceUsage

- hack/test.sh
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
Before this CL, we assumed gcr.io for the docker registry. This CL
allows a developer to set any docker registry.
> pkg/kf/testutil: use DOCKER_REGISTRY for integration tests

- pkg/reconciler/app/controller.go
- pkg/reconciler/app/reconciler.go
The app reconciler will look at related revisions for each update to an
App. Once the Status of the App has matching LatestReadyRevisionName and
LatestCreatedRevisionName, it will delete all the revisions but the one
with the largest "serving.knative.dev/configurationGeneration".
fixes #335
> pkg/reconciler/app: garbage collect revisions

- pkg/kf/apps/fake/fake_pusher.go
- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
Note my use of container-image throughout the code. This is a trend I started with the CRDs: to move away from the brand name Docker because of OCI. However, in CF the flag is `--docker-image` so I kept that. Maybe we should also add an alias `--container-image`?
The logic in push is too complicated, but I didn't want to muddle this PR by refactoring it.
> Add the --docker-image flag

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/apps/start.go
- pkg/kf/commands/apps/start_test.go
- pkg/kf/commands/apps/stop.go
- pkg/kf/commands/apps/stop_test.go
- pkg/kf/commands/root.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
- pkg/kf/testutil/integration.go
- pkg/reconciler/app/reconciler.go
The commands simply toggle the app.Spec.Instances.Stopped value. The
controller has been updated to delete the knative service if the app is
stopped. This is required because knative will otherwise delete the pods
and bring back a single pod for a while (even if scaling is set to 0):
https://github.com/knative/serving/issues/4098
fixes #282
> pkg/kf/commands/apps: adds start and stop commands

- pkg/kf/apps/client.go
- pkg/kf/apps/fake/fake_client.go
- pkg/kf/apps/log_tailer.go
- pkg/kf/apps/log_tailer_test.go
- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
When the --no-start flag is used, the source code is uploaded and built,
however the knative service is not created.
fixes #289
> pkg/kf/apps: adds --no-start flag to push

- pkg/kf/apps/log_tailer.go
- pkg/kf/apps/log_tailer_test.go
Moves the creation of the channel into another for loop, in case the first channel times out.
Fixes #373
> Continue to watch on push to avoid push timeout

- docs/install/gke.md
If you copy and paste the commands without having the project set in gcloud they won't work (or will use the wrong project) - adding the project manually via `--project` stops that
> Add explicit project ID to commands

- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/commands/apps/testdata/manifest.yml
- pkg/kf/manifest/manifest.go
- pkg/kf/testutil/assertions.go
If a route is not provided via flag or manifest, create a default one
(`<app-name>.<default-space-domain>`).
This CL also adds the following flags:
--routes - Define route strings (similar to manifest) for app
--no-route - Don't add a default route
--random-route - Adds a random route if the app doesn't have route
fixes #393
fixes #291
fixes #290
fixes #175
> pkg/kf/commands/apps: push will create default route

- pkg/apis/kf/v1alpha1/route_types.go
- pkg/apis/kf/v1alpha1/route_types_test.go
- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/apps.go
- pkg/kf/commands/apps/apps_test.go
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/commands/apps/testdata/manifest.yml
- pkg/kf/manifest/manifest.go
- pkg/kf/testutil/integration.go
pkg/kf/commands/apps: ensure push can scale apps
This CL fixes a bug where the scaling flag (`-i --instances`) was not
used while `push`ing an app.
It also adds the `--min-scale` and `--max-scale` flags to `push` along
with their corresponding manifest values (the CLI will display a warning
on STDERR while using the manifest to warn that the manifest values
might change per #95).
It also updates `kf apps` to match `cf apps`. It does NOT show the
actual number of pods, but instead shows the desired scaling (including
auto scaling vs exact).
fixes #429
fixes #313
(This needs to wait on #426)
> pkg/kf/commands/apps: ensure push can scale apps

- docs/install.md
Fixes #427 
Replaced wget command with curl.
> Replaced wget command with curl in mac install instructions

- go.mod
- go.sum
- pkg/kf/commands/apps/push.go
Previously, if a user pointed to a file instead of a directory, the
resulting source code container would be empty. This CL fixes that.
fixes #253
> pkg/kf/commands/apps: allow for path to point to a file

- pkg/apis/kf/v1alpha1/utils.go
- pkg/apis/kf/v1alpha1/utils_test.go
- pkg/kf/apps/fake/fake_client.go
- pkg/kf/apps/zz_generated.client.go
- pkg/kf/commands/spaces/create.go
- pkg/kf/commands/spaces/create_test.go
- pkg/kf/internal/tools/clientgen/gentest/client_test.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/tmplclient.go
- pkg/kf/internal/tools/clientgen/tmplheader.go
- pkg/kf/routes/fake/fake_client.go
- pkg/kf/routes/zz_generated.client.go
- pkg/kf/sources/fake/fake_client.go
- pkg/kf/sources/zz_generated.client.go
- pkg/kf/spaces/client.go
- pkg/kf/spaces/fake/fake_client.go
- pkg/kf/spaces/zz_generated.client.go
This PR fixes #371 by borrowing concepts from the service catalog.
It adds WaitFor and WaitForE to every generated client which are
utilities to poll a k8s cluster until a predicate is true.
One predicate is provided for each client to allow the CLI to wait
for deletions.
Additionally, a function that checks if a duck type is completed
is added which resolves #377.
> Adds ability to poll until a predicate is done

- pkg/apis/kf/v1alpha1/source_lifecycle.go
- pkg/apis/kf/v1alpha1/utils.go
- pkg/apis/kf/v1alpha1/utils_test.go
- pkg/kf/commands/apps/integration_test.go
- pkg/reconciler/source/reconciler.go
Previously, when a user would try to update an app by pusing again, the
build would seemingly finish instantly. However, the app wasn't actually
updated or readay yet. What was happening was the AppStatus was
returning a stale Source and Build information which was being picked up
by the CLI.
This CL ensures the AppStatus is properly marked as Unknown (instead of
Ready) for app updates.
fixes #372
> pkg/reconciler: AppStatus doesn't display stale Source

- docs/install/gke.md
- pkg/kf/commands/install/gke/gke.go
Fixes # 473
* Changes gke installer to use 1.13.6-gke.13 (from 1.13.7-gke.8)
* Changes gke docs to use 1.13.6-gke.13 (from 1.13.7-gke.8)
```release-note
- Changed available GKE compatibility
```
> revert GKE version for docs and installer

- pkg/kf/manifest/manifest.go
Fixes # n/a
* Fixes grammar in warning message for auto-scaling fields in manifest
```release-note
```
> fix grammar in manifest warning

- pkg/kf/commands/debug.go
- pkg/kf/commands/root.go
Fixes #318 
* Adds a new sub command for printing basic debug info.
```release-note
Added a `debug` sub-command to help debug issues over GitHub and Slack
```
> added debug command

- docs/install/gke.md
Fixes # None
```
$ kf push logspinner --path /tmp/loggregator-tools
[source upload] Uploading /tmp/loggregator-tools to image gcr.io/******/src-space-bw43veqo1l94-logspinner:1565254531116773000
Error: Error publishing image: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
* Add install step for docker credential
> Install: register gcloud as a Docker credential

- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
fixes #445
- don't `kf target` in tests
- use the space's container registry
- RetryPost doesn't attack the app as frequently
```release-note
```
> pkg/kf/commands/apps: fix StopStart integration tests

- pkg/kf/doctor/diagnostic.go
- pkg/kf/testutil/assertions.go
We tend to use table tests which means the assertion is being applied to
several different tests. This CL helps with quickly finding the failing
test
Fixes #
* Adds `Name()` method to `testutil.Failable`
* Adds `Name()` method to `doctor.Diagnostic`
* Adds `t.Name()` as prefix to failure messages.
```release-note
```
> pkg/kf/testutil: prefix failure messages with test name

- .gitmodules
- docs/kf.dev/.gitignore
Previously, Docsy was a submodule but its own embedded submodules failed
because they were in a vendor/ directory that was excluded by our
.gitignore file. This change modifies the .gitignore to allow vendor/
dirs in the docs/ folder, and puts docsy back as a submodule.
> docs: Docsy is a submodule

- hack/check-linters.sh
Fixes # n/a
* Only run misspell linter on go files
*
*
```release-note
```
> hack: only run misspell on go files

- docs/kf.dev/ci/concourse/README.md
- docs/kf.dev/ci/concourse/image/Dockerfile
- docs/kf.dev/ci/concourse/pipelines/website-pipeline.yml
This change adds a Concourse pipeline for building and publishing the
kf.dev static site. The pipeline also includes a task for creating the
Docker image that the build/publish task uses.
Fixes #490
> docs/ci: add CI to build and push static site

- pkg/kf/commands/apps/scale.go
Minor issue/typo in the kf CLI utility internal help for the `scale` command.
* Display only a single leading dash in the tool-internal help.
```release-note
Fixed typo in the kf CLI utility internal help for the `scale` command.
```
> Single-character flag needs only single leading '-'

- pkg/apis/kf/v1alpha1/space_defaults.go
- pkg/apis/kf/v1alpha1/space_defaults_test.go
We aren't currently enforcing log access, so we should always show the
developer has access.
related to #458
* Default `space.Spec.Security.EnableDeveloperLogsAccess` to true
*
*
```release-note
Added default to `space.Spec.Security.EnableDeveloperLogsAccess`
```
> pkg/apis/kf/v1alpha1: default EnableDeveloperLogsAccess to true

- ci/concourse/pipelines/kf-pipeline.yml
- hack/README.md
- hack/build-release.sh
- hack/upload-release.sh
This pipeline allows kf to deliver versions (e.g., 0.1). It will upload
a tag and release artifacts to github.
related to #168 
* Adds release job to concourse pipeline
*
*
```release-note
Added new job in pipeline
```
> ci/concourse/pipeline: adds release job

- pkg/kf/commands/config/config.go
Before this CL, if a user does not have a $HOME/.kube/config, commands
like `kf version` and `kf install` would still fail.
This CL fixes that by returning a `rest.Config` that has a `Dial`
function that will always return an error if the config failed to load.
fixes #504
Fixes #
* Only return config error if the kube config is used
*
*
```release-note
Changes when a kube config error is returned
Fixed kube config being required for commands like version and install
```
> pkg/kf/commands/config: lazily return kube config errors

- pkg/kf/apps/zz_generated.client.go
- pkg/kf/apps/zz_generated.clientoptions.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
- pkg/kf/internal/tools/clientgen/tmplclient.go
- pkg/kf/internal/tools/generator/gen.go
- pkg/kf/internal/tools/option-builder/option-builder.go
- pkg/kf/routeclaims/zz_generated.client.go
- pkg/kf/routeclaims/zz_generated.clientoptions.go
- pkg/kf/routes/zz_generated.client.go
- pkg/kf/routes/zz_generated.clientoptions.go
- pkg/kf/sources/zz_generated.client.go
- pkg/kf/sources/zz_generated.clientoptions.go
- pkg/kf/spaces/zz_generated.client.go
- pkg/kf/spaces/zz_generated.clientoptions.go
Fixes # 433
* Update generators to use proper casing for WithXXX functions
*
*
```release-note
Changed generated function names
```
> pkg/kf/internal/tools: title casing for WithXXX

- pkg/kf/commands/service-bindings/vcap_services.go
- pkg/kf/commands/service-bindings/vcap_services_test.go
*
*
*
```release-note
Fixed vcap-service double decoding secrets
```
> do not base64 decode vcap services

- pkg/reconciler/app/resources/route.go
- pkg/reconciler/base.go
- pkg/reconciler/route/controller.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
Fixes #521
Fixes #535 
* Watch for VirtualService changes per namespace (instead of by controller)
* Don't manage the OwnerReferences for VirtualServices (let K8s do it) (#521)
* Ensure regexp path matcher doesn't have extra `/` (#535)
```release-note
Fix how VirtualServices are watched in route controller
Fix how VirtualService OwnerReferences are managed
Fix how regexp path matchers are created
```
> pkg/reconciler/route: recreate deleted VirtualServices

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
- pkg/reconciler/app/reconciler.go
Fixes #544
* App reconciler doesn't an error if the app is stopped
* Mark app status as Unknown when app is stopped
*
```release-note
Fixed bug where stopped apps cause app reconciler to return error (#544)
```
> pkg/reconciler/app: handle when app is stopped

- docs/kf.dev/content/en/docs/operators/customizing-buildpacks/_index.md
This change adds the "Customizing Buildpacks" guide to the operators
section of the docs website.
> docs: Document "Customizing Buildpacks"

- pkg/kf/commands/service-bindings/bind-service.go
Fixes #569
* Display tip to user to restart the app after binding a service
*
*
```release-note
Added tip to bind-service command
```
> pkg/kf/commands/service-bindings: tip user to restart app

- pkg/kf/commands/config/config.go
- pkg/kf/commands/config/config_test.go
Fixes #461
* Supported `KUBECONFIG` env var as default kubeconfig
```release-note
Added `KUBECONFIG` env var as default kubeconfig
```
> Supports KUBECONFIG when initKubeConfig

- pkg/reconciler/app/controller.go
- pkg/reconciler/app/reconciler.go
- pkg/reconciler/base.go
- pkg/reconciler/route/controller.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/source/controller.go
- pkg/reconciler/source/reconciler.go
- pkg/reconciler/space/controller.go
- pkg/reconciler/space/reconciler.go
* remove logger from reconciler Base
* always get logger form the context
* make some log lines debug instead of info
This PR fixes a few errors in the way we are handling logs on the controller.
For controllers: the context given at creation time is not the same context as the one at run time. So instead of creating a logger ans saving it to the reconciler base, the logger should always be created from the current context. This fixes missing logs, plus it adds the knative traceid to all of our logs. 
```release-note
Updated kf controller logs
```
> Fix reconciler logs

- pkg/kf/commands/services/helpers_test.go
- pkg/kf/commands/services/services.go
- pkg/kf/commands/services/services_test.go
Fixes #597
* Change kf services output to list all service instances. It will not immediately return an error (and miss listing other service instances) when a service instance is invalid
Previous output:
```
Name                 Service       Plan       Bound Apps  Last Operation           Broker
Error: class 'blah' not found in cluster scope
```
New output:
```
Name                 Service       Plan       Bound Apps  Last Operation                     Broker
myservice            blah          blahplan               ReferencesNonexistentServiceClass  error finding broker: class 'blah' not found in cluster scope
spring-music-db      postgresql    11-4-0     envs-app    ProvisionedSuccessfully            minibroker
```
> update kf services output

- pkg/kf/commands/install/gke/gke.go
Fixes #
* Silence usage message for error in PreRun in `kf install gke`
*
*
```release-note
Changed how the GKE install looks when alpha or beta are not enabled
```
> pkg/kf/commands/install/gke: SilenceUsage for PreRun

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_bind-service.md
- pkg/kf/apps/client.go
- pkg/kf/apps/client_test.go
- pkg/kf/cfutil/systemenvinjector_test.go
- pkg/kf/cfutil/vcap.go
- pkg/kf/cfutil/vcap_test.go
- pkg/kf/commands/service-bindings/bind-service.go
- pkg/kf/commands/service-bindings/bind-service_test.go
- pkg/kf/commands/service-bindings/integration_test.go
- pkg/kf/service-bindings/client.go
- pkg/kf/service-bindings/fake/fake_client_interface.go
Fixes #608 
* Use `kfv1alpha1.ComponentLabel` instead of the previously correct label to name services
* Added integration tests for vcap service format
```release-note
```
> fixes #608

- pkg/reconciler/app/reconciler.go
Fixes #609
* Don't GC all ready revisions
*
*
```release-note
Fixed bug where GC would remove ready revision leaving unready one
```
> pkg/reconciler/app: gc after revision is ready

- ci/concourse/pipelines/pr-pipeline.yml
- hack/integration-test.sh
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/service-bindings/integration_test.go
- pkg/kf/testutil/integration.go
Fixes #
* Run unit and integration tests in separate tasks
* Run integration tests per package
*
```release-note
```
> ci: break unit and integration tests out

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_restage.md
- pkg/kf/apps/client.go
- pkg/kf/apps/fake/fake_client.go
- pkg/kf/apps/log_tailer.go
- pkg/kf/apps/push.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/restage.go
- pkg/kf/commands/apps/restage_test.go
Fixes #636 
* Adds log tailing to restage
* Refactors the Restage client command to also return the app so that the deploy logs can get the needed info
* Refactors DeployLogs to add another command that will retrieve all info needed off an app to be used by both push and restage (maybe also restart in the future?)
```release-note
Added log tailing to the `restage` command
```
> made restage return logs

- pkg/kf/cfutil/fake/fake_systemenvinjector.go
- pkg/kf/cfutil/systemenvinjector.go
- pkg/kf/cfutil/systemenvinjector_test.go
- pkg/kf/cfutil/vcap.go
- pkg/kf/cfutil/vcap_test.go
- pkg/kf/commands/service-bindings/integration_test.go
- samples/apps/service-broker/go.mod
- samples/apps/service-broker/go.sum
- samples/apps/service-broker/main.go
Fixes #637 
* Added support for inserting tags from service instances into VCAP_SERVICES
```release-note
Added support for inserting tags from service instances into `VCAP_SERVICES`
```
> added service tags

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
- pkg/kf/apps/log_tailer.go
- pkg/reconciler/app/reconciler.go
Fixes #607 
* Makes the reconciler always update the ObservedGeneration on Apps in accordance with the Kubernetes controller guidlines
* Ensure Knative Serving updates aren't prematurely updated if there is a generation mismatch 
```release-note
```
> fixed #607

- pkg/kf/commands/service-bindings/integration_test.go
- pkg/kf/commands/services/services.go
- pkg/kf/services/services.go
* Update `services` command to properly get broker, class, and plan name (found by running int tests locally)
* Add relevant issue numbers in skipped service-bindings integration test (flaky but passed locally)
```release-note
```
> Fix services cmd and add issue numbers to skipped int tests

- go.mod
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/commands/config/config.go
- pkg/kf/describe/describe.go
- pkg/kf/internal/tools/clientgen/client.go
- pkg/kf/internal/tools/clientgen/genclient.go
- pkg/kf/internal/tools/option-builder/option-builder.go
- pkg/kf/manifest/manifest.go
#463 
* Use K8s YAML parser everywhere
```release-note
Changed default YAML parser to be `sigs.k8s.io/yaml`
```
> moved to using k8s yaml parser everywhere

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_app.md
- go.mod
- go.sum
- pkg/kf/commands/apps/app.go
- pkg/kf/commands/apps/integration_test.go
- pkg/kf/testutil/integration.go
- third_party/VENDOR-LICENSE
Adds the ability to print output with k8s printers and replaces the route check in integration tests to use the JSON output because the raw output is causing #653 to fail.
> Allow printing with k8s printers

- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_test.go
Part of #656 
* Added support for the legacy `buildpack` manifest field
```release-note
Added support for the legacy `buildpack` manifest field
```
> added support for the legacy buildpack field

- pkg/kf/apps/client.go
- pkg/kf/apps/zz_generated.client.go
- pkg/kf/apps/zz_generated.clientoptions.go
- pkg/kf/commands/routes/delete_route.go
- pkg/kf/internal/tools/clientgen/common-options.yml
- pkg/kf/internal/tools/clientgen/gentest/client.go
- pkg/kf/internal/tools/clientgen/gentest/client_test.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.client.go
- pkg/kf/internal/tools/clientgen/gentest/zz_generated.clientoptions.go
- pkg/kf/internal/tools/clientgen/tmplclient.go
- pkg/kf/internal/tools/clientgen/tmplfunctional.go
- pkg/kf/routeclaims/client.go
- pkg/kf/routeclaims/zz_generated.client.go
- pkg/kf/routeclaims/zz_generated.clientoptions.go
- pkg/kf/routes/client.go
- pkg/kf/routes/zz_generated.client.go
- pkg/kf/routes/zz_generated.clientoptions.go
- pkg/kf/sources/client.go
- pkg/kf/sources/zz_generated.client.go
- pkg/kf/sources/zz_generated.clientoptions.go
- pkg/kf/spaces/client.go
- pkg/kf/spaces/zz_generated.client.go
- pkg/kf/spaces/zz_generated.clientoptions.go
* Removed unused generation options that were created for when we were doing things client-side. This is preliminary cleanup before I add stuff for #599 
```release-note
```
> removed unused generator options

- ci/concourse/pipelines/pr-pipeline.yml
- hack/check-code-generator.sh
This change moves env setup code required to run check-code-generator.sh
from Concourse pipeline task into check-code-generator.sh itself. This
allows the script to be run from other pipelines without replicating the
env setup code.
> ci: Improve code generation script

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_push.md
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/commands/root_test.go
- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_test.go
- pkg/kf/manifest/manifest_validation_test.go
- pkg/kf/services/fake/fake_client.go
- pkg/kf/services/zz_generated.client.go
Related to #95
* Fixed the warning about unofficial fields to show all Kf added fields.
* Added manifest fields for HTTP2 and no-start to match CLI flags so an app can be (almost) entirely declarative.
* Changed the `--grpc` flag to `--enable-http2` to reflect what's actually happening in Knative Serving.
```release-note
Fixed the warning about unofficial fields to show all Kf added fields.
Added manifest fields for HTTP2 and no-start to match CLI flags so an app can be (almost) entirely declarative.
Changed the `--grpc` flag to `--enable-http2` to reflect what's actually happening in Knative Serving.
```
> moved unofficial fields out of manifest proper

- hack/update-codegen.sh
Fixes #715
* Make `./hack/update-codegen.sh` fail for invalid arg
*
*
```release-note
```
> hack: update-codegen.sh rejects invalid arg

- hack/check-code-generator.sh
* move check-code-generator.sh to use bash because `[[` isn't supported in `sh` which we're using to check the GOPATH due to https://github.com/kubernetes-sigs/kubebuilder/issues/359
> change check-code-generator to bash

- pkg/kf/commands/install/gke/gke.go
Fixes #720
* GKE installer doesn't set cluster version
*
*
```release-note
Fixed installer using deprecated GKE version
```
> pkg/kf/commands/install/gke: use default GKE

- pkg/kf/apps/kfapp.go
- pkg/kf/apps/kfapp_test.go
- pkg/kf/apps/push-options.yml
- pkg/kf/apps/push.go
- pkg/kf/apps/push_options.go
- pkg/kf/apps/push_test.go
- pkg/kf/commands/apps/push.go
- pkg/kf/commands/apps/push_test.go
- pkg/kf/manifest/manifest_conversion.go
- pkg/kf/manifest/manifest_conversion_test.go
- pkg/kf/manifest/manifest_validation.go
- pkg/kf/manifest/manifest_validation_test.go
Cleanup before continuing #656 
The step after this is creating a full container definition from the manifest, then a full `v1alpha1.App` once source can be created. This will allow us to print diffs before push or just dump a yaml instead while reducing the dizzying array of options to Push.
* Pass complete scaling and quota objects to pusher.
* Use validator to notify of bad config.
```release-note
```
> changed manifest to produce sub-types

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_map-route.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_restart.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_scale.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_set-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_start.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_stop.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unmap-route.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_unset-env.md
- pkg/kf/apps/client.yml
- pkg/kf/apps/fake/fake_client.go
- pkg/kf/apps/zz_generated.client.go
- pkg/kf/commands/apps/logs_test.go
- pkg/kf/commands/apps/restart.go
- pkg/kf/commands/apps/restart_test.go
- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/scale_test.go
- pkg/kf/commands/apps/set_env.go
- pkg/kf/commands/apps/set_env_test.go
- pkg/kf/commands/apps/start.go
- pkg/kf/commands/apps/start_test.go
- pkg/kf/commands/apps/stop.go
- pkg/kf/commands/apps/stop_test.go
- pkg/kf/commands/apps/unset_env.go
- pkg/kf/commands/apps/unset_env_test.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/map_route_test.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/commands/routes/unmap_route_test.go
Part of #599 
* Add the ability to wait for Knative Service sync and Routes sync to apps.
* Using those, change all app transformation functions to wait until the thing they changed is completed.
* Replace the output for the logs tests to be a buffer so it stops writing into our test output.
* Change a few of the tests to normalize them with the other tests in their package
```release-note
Changed the `restart` command to now be synchronous by default
Changed the `scale` command to now be synchronous by default
Changed the `stop` command to now be synchronous by default
Changed the `start` command to now be synchronous by default
Changed the `set-env` command to now be synchronous by default
Changed the `unset-env` command to now be synchronous by default
Changed the `map-route` command …
```
> changed apps commands to support async

- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
All other domains must no longer be labeled as default.
Fixes #
*
*
*
```release-note
```
> Fix configure-space set-default-domain

- pkg/kf/apps/push.go
- pkg/kf/apps/push_test.go
Fixes #738
* Fixed push to ensure services bindings are preserved
*
*
```release-note
Fixed push to ensure services bindings are preserved
```
> pkg/kf/apps: ensure ServiceBindings are preserved

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/kf/commands/routes/integration_test.go
- pkg/kf/testutil/integration.go
- pkg/reconciler/app/reconciler.go
* Fixes bug where `map-route` command was hanging. Mark `RouteReady` condition as True when routes and routeclaims are reconciled successfully
* Add integration test for map-route
```release-note
Fixed hanging route commands bug
```
> fix routes ready status on app

- docs/kf.dev/ci/concourse/pipelines/website-pipeline.yml
This change publishes docs from the develop branch to the IAP-protected
App Engine site at https://kf-dev-site.appspot.com
> docs: Publish develop branch as default

- pkg/apis/kf/v1alpha1/source_lifecycle.go
- pkg/apis/kf/v1alpha1/source_lifecycle_test.go
- third_party/knative-build/pkg/apis/build/v1alpha1/build_types.go
- third_party/knative-build/pkg/logs/logs.go
Fixes #
* Moves ./third_party/knative-build's `Status` type to use v1beta1 (from v1alpha1). This is possible as both types are semantically the same. (This is a small step towards using Tekton as it moves the build status handling into the same pattern other CRDs use.)
*
*
```release-note
Changes knative-build's Status type to v1beta1 (from v1alpha1).
```
> third_party/knative-build: move Status to v1beta1

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- ci/concourse/terraform/main.tf
This change pins the Terraform version for tests that occur during
release.
> ci: Pin Terraform version

- hack/flatten-supported-gke-versions.py
- hack/scrape-supported-gke-versions.py
* Add scripts to scrape Cloud Run documentation for knowing which versions of Cloud Run are available on which versions
of GKE
./hack/scrape-supported-gke-versions.py
```
[{"cloud_run_version": "0.8.1-gke.0", "gke_versions": ["1.14.6-gke.13", "1.13.10-gke.7", "1.12.10-gke.11"]}, {"cloud_run_version": "0.8.0-gke.0", "gke_versions": ["1.13.10-gke.0", "1.12.10-gke.5"]}, {"cloud_run_version": "0.6.1-gke.1", "gke_versions": ["1.13.9-gke.3", "1.13.7-gke.24", "1.12.9-gke.16", "1.12.9-gke.15"]}]
```
./hack/scrape-supported-gke-versions.py | ./hack/flatten-supported-gke-versions.py
```
[{"gke_version": "1.12.10-gke.11", "cloud_run_version": "0.8.1-gke.0"}, {"gke_version": "1.12.10-gke.5", "cloud_run_version": "0.8.0-gke.0"}, {"gke_version": "1.12.9-gke.15", "cloud_run_version": "0.6.1-gke.1"}, …
```
> Add scripts to scrape Cloud Run documentation

- pkg/kf/commands/apps/integration_test.go
Does not fix #730 properly, but applies a larger band aid to the wound.
```release-note
```
> add more time to flaky test

- hack/update-codegen.sh
Thanks to
https://github.com/kubernetes-sigs/kind/blob/10642f530782963ed23b3d4a14587950bbacaa63/hack/update-generated.sh
Fixes #
* Create fake GOPATH when running the code generator
```release-note
```
> Fix hack/update-codegen.sh so it takes 1 min

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_delete-space.md
- pkg/kf/commands/spaces/delete.go
- pkg/kf/commands/spaces/delete_test.go
#599 
* Changes `delete-space` to be synchronous by default
```release-note
Changed `delete-space` to be synchronous by default
```
> made spaces synchronous

- pkg/kf/apps/log_tailer.go
- pkg/kf/apps/log_tailer_test.go
Previous to this CL, our log stream would sometimes spit out:
Fixes #793
* Logging stop watching Pod once resource is old
*
*
```release-note
Fixed logging bug where old pods are still being watched
```
> pkg/kf/apps: handle metav1.Status failures in logs

- pkg/apis/kf/v1alpha1/space_lifecycle.go
- pkg/apis/kf/v1alpha1/space_lifecycle_test.go
- pkg/reconciler/space/controller.go
- pkg/reconciler/space/reconciler.go
- pkg/reconciler/space/resources/build_service_account.go
- pkg/reconciler/space/resources/build_service_account_test.go
Fixes #
* Space reconciler creates a service account per space. The SA does not have any secrets (yet). It will eventually be used by build pipelines for uploading containers.
*
*
```release-note
Added feature for space reconciler to add service account
```
> pkg/reconciler/space: add build Service Account

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_append-domain.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-buildpack-builder.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-buildpack-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-container-registry.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-domains.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-execution-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_remove-domain.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-buildpack-builder.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-buildpack-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-container-registry.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-default-domain.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_unset-buildpack-env.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_unset-env.md
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
* configure-space uses the targeted namespace by default
```release-note
```
> Make space an optional arg to configure-space

- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_get-build-service-account.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_configure-space_set-build-service-account.md
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_create-space.md
- pkg/kf/commands/spaces/config_space.go
- pkg/kf/commands/spaces/config_space_test.go
- pkg/kf/commands/spaces/create.go
- pkg/kf/commands/spaces/create_test.go
- pkg/kf/commands/spaces/get.go
- pkg/kf/commands/spaces/get_test.go
- pkg/kf/spaces/kfspace.go
- pkg/kf/spaces/kfspace_test.go
Fixes #785 
* Adds way to configure BuildServiceAccount for spaces
*
*
```release-note
Adds way to configure space's BuildServiceAccount property
```
> pkg/kf/commands/spaces: configure BuildServiceAccount

- ci/concourse/pipelines/pr-unipipeline.yml
Simply unified PR pipeline by not executing release scripts or generating licenses. Also, use the correct repo and branch for the ci-pipelines-src resource.
> ci: add unified PR pipeline

- pkg/apis/kf/v1alpha1/source_lifecycle.go
- pkg/apis/kf/v1alpha1/source_lifecycle_test.go
- pkg/reconciler/app/controller.go
- pkg/reconciler/app/reconciler.go
- pkg/reconciler/base.go
- pkg/reconciler/source/controller.go
- pkg/reconciler/source/reconciler.go
- pkg/reconciler/source/resources/build.go
- pkg/reconciler/source/resources/build_test.go
Fixes #
* Moves Builds to reference Secrets for environment variables.
*
*
```release-note
Changed the way Build stores environment variables to use Secrets
```
> pkg/reconciler/source: move Build to use Secrets

- pkg/apis/kf/v1alpha1/source_lifecycle_test.go
- pkg/reconciler/source/reconciler.go
Fixes #
* This CL fixes a bug where the Secret status is only propagated if there
is an envs secret. Docker builds for example don't require a secret but
the Status still needs to be set to true.
*
*
```release-note
```
> pkg/reconciler/source: fix Secret Status

- pkg/kf/commands/install/gke/gke.go
Fixes #816
* Uses regexp filter to ensure exact match
*
*
```release-note
Fixed installer selecting prefix instead of exact match for things like projects or clusters
```
> pkg/kf/commands/install/gke: fix cluster zlone selection

- pkg/kf/istio/istio_client_options.go
- pkg/kf/istio/istio_client_options.yml
- pkg/kf/istio/istio_client_test.go
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
* Update fields in virtualservices to support naming discrepancies in upgraded GKE/knative serving versions (see #805)
* Change default Istio Ingress namespace and Ingress svc name
* Change Knative ingress gateway and change route destination to cluster-local-gateway
```release-note
Added routing support for GKE versions 1.13.10 and greater
Changed BREAKING default ingress gateways
```
> Update gateway names and namespaces

- pkg/kf/commands/install/gke/gke.go
Fixes #823
* Add a question to the `kf install gke` command to ask which IP addr to hit when targeting the cluster
Note that more setup differences might be required for creating private GKE clusters, but this is an easy question to answer.
```release-note
```
> Ask user for public/internal GKE server IP

- pkg/kf/apps/log_tailer.go
- pkg/kf/apps/log_tailer_test.go
This PR adds additional debugging information to `kf push` and fixes our watchers to use the types sent by events to detect things like errors and app deletions.
> updated push event watcher

- hack/update-codegen.sh
turn on go modules for tidy because it's turned off earlier in this script
> turn on go111module

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- ci/concourse/terraform/main.tf
* remove network selflink because it's no longer used
* remove ip_allocation_policy because Terraform gives the following instructions: `This field is being removed in 3.0.0. If set to true, remove it from your config.`
```release-note
```
> fix terraform in ci

- config/300-buildpack-clustertask.yaml
- config/300-kaniko-clustertask.yaml
There is an issue with Tekton where it will sometimes assume an array
type if the type is not specified. This is easily fixed by explicitly
stating it as a string.
Fixes #
* explicitly state input types as strings
*
*
```release-note
Fixed bug where Tekton sometimes assumes inputs should be an array.
```
> config: explicitly state input types as strings

- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/terraform/main.tf
- hack/create-gke-secret.sh
* Use Terraform to manage the key for authenticating to GCR.
* Reduce the number of subnetworks created by Terraform.
> Use Terraform for Service Accounts and Subnetworks

- pkg/kf/commands/install/gke/gke.go
Previous to this CL, the installer wouldn't return an error if the
clsuter failed to create.
Fixes #
* GKE installer fails when the cluster fails to create
*
*
```release-note
```
> pkg/kf/commands/install/gke: fail when cluster fails to create

- ci/concourse/pipelines/nightly-release-pipeline.yml
- ci/concourse/pipelines/pr-unipipeline.yml
- ci/concourse/pipelines/release-pipeline.yml
- ci/concourse/terraform/main.tf
- docs/kf.dev/content/en/docs/general-info/kf-cli/commands/kf_install_gke.md
- pkg/kf/cli/prompts.go
- pkg/kf/commands/install/gke/gke.go
* Move the Terraform to use GKE Release channels
* Move the installer to allow release channel selection
```release-note
Added the ability for the installer to pick a release channel.
```
> moved to release channels on GKE

- cmd/controller-init/main.go
Note: This one has to wait for #892 to be merged
Fixes #890
* Create placeholder ConfigMap (`config-secrets`) if missing from kf namespace
*
*
```release-note
Fixed bug where controller enters crashloop when kf is first installed
```
> cmd/controller-init: add config-secrets if not present

- pkg/kf/manifest/manifest_conversion.go
- pkg/kf/manifest/manifest_conversion_test.go
* Kf properly sets both the liveness probe in addition to the readiness probe that was already set correctly.
> Create containers with both liveness and readiness probes

- pkg/apis/kf/v1alpha1/app_defaults.go
- pkg/apis/kf/v1alpha1/app_defaults_test.go
This ensures probes set won't get a 1 second timeout on the probe which is causing some applications to crash.
* Default liveness probes on Apps.
```release-note
Changed: App liveness probes now get defaults that match readiness probes
```
> Fix webhook defaulting for probes.

- docs/content/en/docs/v2.11/developer/build-and-deploy/manifest.md
- pkg/apis/kf/k8s_fieldmask.go
- pkg/apis/kf/k8s_fieldmask_test.go
- pkg/apis/kf/k8s_validation.go
- pkg/apis/kf/k8s_validation_test.go
- pkg/kf/commands/exporttok8s/exporttok8s.go
- pkg/kf/commands/exporttok8s/exporttok8s_test.go
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_have_manifest_but_no_cpu_diskquota_memory_container.golden
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_have_manifest_but_no_health_check_container.golden
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_have_manifest_with_the_properties_container.golden
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_no_manifest_container.golden
- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_conversion.go
- pkg/kf/manifest/manifest_conversion_test.go
- pkg/kf/manifest/manifest_validation.go
- pkg/kf/manifest/manifest_validation_test.go
- pkg/reconciler/app/resources/deployment.go
- pkg/reconciler/app/resources/deployment_test.go
- samples/apps/slowpoke/go.mod
- samples/apps/slowpoke/main.go
- samples/apps/slowpoke/manifest.yaml
Kf was originally written before K8s supported startupProbe. Now that it does, we can better match what Diego does. Diego starts with a quick probe that repeatedly checks until the app reports health the first time then switches to a less frequent probe.
Under the old logic Kf used the timeout in the probes and retries to try and achieve a pseudo-startupProbe which may have left zombie routes for too long after an application had crashed. This PR aims to clean all this up by doing the following:
* Allowing the use of startupProbes in the app's container template.
* Defaulting the startupProbe port number to match the app's primary port.
* Updating the client-side logic that sets up probes to match Diego.
* Allowing developers to override this with new manifest fields.
* Adding support for …
> Support startup probe

- pkg/kf/apps/push.go
- pkg/kf/apps/push_test.go
* Added App OwnerReference to bindings for `kf push` command
* ServiceInstanceBindings are now garbage collected when referenced Apps are deleted
> Bind brokered services to apps

- config/200-clusterrole.yaml
Kf controller populates rules for the clusterole, which is conflicting with Kf operator
> Make ClusterRole `EnsureExists`

- docs/content/en/docs/v2.11/developer/build-and-deploy/manifest.md
- docs/content/en/docs/v2.11/developer/scaling/resource-management.md
- pkg/apis/kf/v1alpha1/app_defaults.go
- pkg/apis/kf/v1alpha1/app_defaults_test.go
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_have_manifest_but_no_health_check_container.golden
- pkg/kf/commands/exporttok8s/testdata/golden/testgetcontainer_have_manifest_with_the_properties_container.golden
- pkg/kf/manifest/manifest.go
- pkg/kf/manifest/manifest_conversion.go
- pkg/kf/manifest/manifest_conversion_test.go
- pkg/kf/manifest/manifest_test.go
This change reverts the previous change that forced apps defining a CPU in the manifest to use that as both lower and upper bound.
It restores the behavior that by default apps will have no upper-bound and instead will only get the lower-bound if they set CPU.
Apps that want to set an upper-bound should use the new cpu-limit property instead.
There's also a new document outlining how resources work in Kf to
explain the caveats around setting CPUs.
> Cpu limits

- config/config-defaults.yaml
- operator/pkg/apis/kfsystem/kf/defaults.go
- pkg/apis/kf/config/defaults.go
- pkg/apis/kf/config/defaults_test.go
- pkg/apis/kf/config/store_test.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
- pkg/apis/kf/v1alpha1/route_lifecycle.go
- pkg/apis/kf/v1alpha1/route_lifecycle_test.go
- pkg/reconciler/route/controller.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/route/reconciler_test.go
- pkg/reconciler/route/resources/virtual_service.go
Default to not track conditions of VirtualService when reconciling Routes.
Status change is causing too much updates to VirtualService.
> Add setting to not track conditions of VirtualService when reconciling

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
- pkg/reconciler/app/resources/deployment.go
- pkg/reconciler/app/resources/deployment_test.go
Volumes were being polled from the k8s api which can cause unsorted lists. If multiple volumes were attached to an application it could cause the application instance to be infinitely reconciled.
> Fixed nondeterministic volume statues.

- pkg/kf/commands/root.go
- pkg/kf/commands/service-bindings/fix-orphaned-bindings.go
- pkg/kf/commands/service-bindings/fix-orphaned-bindings_test.go
- pkg/kf/commands/wire_gen.go
- pkg/kf/commands/wire_injector.go
Due to a bug in earlier versions of Kf, bindings created in app manifests weren't getting owner references.
This change creates a new command: fix-orphaned-bindings to clean them up in two cases:
1. Where a binding has no owning app.
2. Where a binding's owning app was deleted.
It allows both a dry-run mode (default) which prints out equivalent kubectl commands and an actuation mode which uses the K8s API to perform the updates.
> Add command to fix binding owners.

- cmd/generate-release/scripts/create_dm_deployment.bash
stop using docker image type which is deprecated from GKE 1.24
> Fix deployment manager image type

- config/config-defaults.yaml
- docs/content/en/docs/v2.11/operator/customizing/customizing-features.md
- operator/pkg/apis/kfsystem/kf/defaults.go
- pkg/apis/kf/config/defaults.go
- pkg/apis/kf/config/defaults_test.go
- pkg/apis/kf/config/store_test.go
- pkg/reconciler/route/reconciler.go
- pkg/reconciler/route/resources/testdata/golden/testmakevirtualservice_no_retries_applies_everywhere_virtualservice.golden
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
Adds a new flag that allows disabling of retries in VirtualService routes. This may cause some applications to work better in Kf if they can't handle retries on their requrests and/or return status codes that mirror what is typically sent by HTTP routing infrastructure and cause Istio to retry.
By default, we leave this behavior off because it's recommended to use Istio's settings to hide instability in the mesh.
Ideally this setting could be done per-app, but Istio ony allows it per HTTP destination meaning routes (which can send traffic to multiple apps) don't fit cleanly.
> Allows users to disable retries across the cluster.

- config/config-defaults.yaml
- docs/content/en/docs/v2.11/operator/customizing/customizing-features.md
- operator/pkg/apis/kfsystem/kf/defaults.go
- pkg/apis/kf/config/defaults.go
- pkg/apis/kf/config/defaults_test.go
- pkg/apis/kf/config/store_test.go
- pkg/reconciler/app/reconciler.go
- pkg/reconciler/app/reconciler_test.go
This fixes the existing start command behavior which panics.
It additionally adds the following:
* Tests for the different start command lookup scenarios.
* A way to enable/disable the behavior.
I've validated by installing in a cluster and trying with apps with the global value enabled and disabled and was able to reproduce the panic in the old code with the tests and confirm that it no longer occurs.
> Allow start commands to be displayed.

- cmd/generate-release/scripts/Dockerfile.deployer
- cmd/generate-release/scripts/install-asm.bash
- config/config-defaults.yaml
- docs/content/en/docs/v2.11/operator/customizing/customizing-features.md
- operator/pkg/apis/kfsystem/kf/defaults.go
- pkg/apis/kf/config/defaults.go
- pkg/apis/kf/config/defaults_test.go
- pkg/apis/kf/config/store_test.go
- pkg/kf/commands/dependencies/dependencies.go
- pkg/reconciler/route/resources/testdata/golden/testmakevirtualservice_route_host_ignoring_port_using_prefix_virtualservice.golden
- pkg/reconciler/route/resources/virtual_service.go
- pkg/reconciler/route/resources/virtual_service_test.go
In cf, an http request with a ```Host``` header containing a port number (e.g. example.com:443) is routed by ignoring the port number (e.g. example.com:443 matches to example.com). 
Currently if a port number is included in the ```Host``` header on an http request to kf it will not match with any virtual service.  For parity with cf, kf should ignore port numbers when matching is happening by using a prefix instead of an exact match.
For now the ability to ignore port specified in the ```Host``` header will be implemented behind the routeHostIgnoringPort 
flag.
Istio version 1.15+ is needed for the feature to function correctly
> Allow for requests with Host header to be routed by ignoring any speified port as part of the header value

- pkg/apis/kf/v1alpha1/app_lifecycle.go
- pkg/apis/kf/v1alpha1/app_lifecycle_test.go
The status.urls field is generated from the list of all routes attached to the app, even if they're no longer desired. This makes the VCAP_APPLICATION to change each time an app is stopped and then started. Consequentially, triggering a new rollout of the app that is later killed wasting resources.
* Add deduping mechanism for status.urls when propagating Route Status. 
* Exclude orphaned routes urls from AppStatus.urls this will allow the env variable VCAP_APPLICATION to only contain  the urls of the desired routes.
> Exclude orphaned bindings and dedupe status.urls

- docs/content/en/docs/v2.11/examples/deploying-docker-apps-with-nfs-mapfs.md
- pkg/reconciler/build/resources/builtin_tasks.go
- third_party/mapfs/src/mapfs/mapfs.go
Fix segment fault with mapfs, fusesidecar image is released separately to gcr.io/kf-releases/fusesidecar:v2.11.14
> Fix segment fault with mapfs

- docs/content/en/docs/v2.11/examples/deploy-with-offline-java-builder.md
- Adds a new page to our docs describing how to use an offline Java buildpack with Kf
> Create deploy-with-offline-java-builder docs

- ci/cloudbuild/release-and-test.yaml
* Post submit workflows fail due to misconfigured attempts to write results to testgrid. Testgrid results are only expected for daily runs.
> Fix default substitutions for post submit workflow

- .devcontainer/Dockerfile
- ci/cloudbuild/test.yaml
- ci/cloudbuild/unit-test.yaml
- cmd/generate-release/cloudbuild.yaml
- pkg/client/kf/clientset/versioned/fake/register.go
- pkg/client/kf/clientset/versioned/scheme/register.go
- pkg/client/kube-aggregator/clientset/versioned/fake/register.go
- pkg/client/kube-aggregator/clientset/versioned/scheme/register.go
- pkg/client/kube/clientset/versioned/fake/register.go
- pkg/client/kube/clientset/versioned/scheme/register.go
- pkg/client/networking/clientset/versioned/fake/register.go
- pkg/client/networking/clientset/versioned/scheme/register.go
* Bump go version used to build Kf to golang 1.20. go1.17 is now sufficiently old that we need to update to use newer versions of our dependencies.
> chore: update Go version to golang:1.20

- pkg/reconciler/apiservercerts/controller.go
- pkg/reconciler/app/controller.go
- pkg/reconciler/build/controller.go
- pkg/reconciler/clusterservicebroker/controller.go
- pkg/reconciler/featureflag/controller.go
- pkg/reconciler/reconcilerutil/stats.go
- pkg/reconciler/reconcilerutil/stats_test.go
- pkg/reconciler/route/controller.go
- pkg/reconciler/servicebroker/controller.go
- pkg/reconciler/serviceinstance/controller.go
- pkg/reconciler/serviceinstancebinding/controller.go
- pkg/reconciler/space/controller.go
- pkg/reconciler/task/controller.go
- pkg/reconciler/taskschedule/controller.go
This PR adds controller metrics logging to all standard Kf controllers. Logs are written to the same loggers the controllers use periodically and hook into the queue system to report on current depth, frequency, etc.
> Added controller metrics logging.

- ci/cloudbuild/release-and-test.yaml
- ci/cloudbuild/test.yaml
- hack/prow/e2e-test.sh
* Prefix e2e test run IDs with the date
* Include cloudbuild ID in metadata for testgrid to ensure results can be linked to a specific cloudbuild execution now that the naming scheme does not reflect the Cloudbuild run.
Prefixing E2E test run IDs with the date improves testgrid compatibility. Testgrid assumes new runs will have lexographically greater IDs. Improving run ordering ensures that testgrid correctly detects new results.
> Update e2e test result naming scheme for better testgrid compatibility

- cmd/generate-release/cloudbuild.yaml
Despite using an upgraded go image in certain steps, the ko image that Kf was using to build still had an outdated version of go (1.17) meaning that there was an inconsistency between local development and what was being produced.
This change pivots us to use the latest version of ko on the current go base image the pipeline uses ensuring Kf will always be built with an expected version of Go, allowing us to stay up to date on features and patches.
> Change the release builder to build ko.

- pkg/kf/commands/apps/scale.go
- pkg/kf/commands/apps/scale_test.go
- pkg/kf/commands/apps/set_env.go
- pkg/kf/commands/apps/set_env_test.go
- pkg/kf/commands/apps/unset_env.go
- pkg/kf/commands/apps/unset_env_test.go
- pkg/kf/commands/autoscaling/create_autoscaling_rule.go
- pkg/kf/commands/autoscaling/delete_autoscaling_rules.go
- pkg/kf/commands/autoscaling/disable_autoscaling.go
- pkg/kf/commands/autoscaling/enable_autoscaling.go
- pkg/kf/commands/autoscaling/update_autoscaling_limits.go
- pkg/kf/commands/autoscaling/update_autoscaling_limits_test.go
- pkg/kf/commands/cluster/config_cluster.go
- pkg/kf/commands/routes/map_route.go
- pkg/kf/commands/routes/unmap_route.go
- pkg/kf/internal/utils/cli/async_flags.go
- pkg/kf/internal/utils/cli/async_flags_test.go
* Introduce async_if_stopped flag which allows commands to terminate without waiting only if they are operating on an app that is in the stopped state.
`Added` async_if_stopped flag to commands that can terminate asynchronously if the app they operate on is in the stopped state.
i.e. with the `scale` command kf will now return very quickly if the app is stopped
```
kf scale myapp --instances 3
Scale:
Stopped?:  true
Replicas:  3
Scaling App "nginx-sample" in Space "gareth" asynchronously because app is stopped
```
> Add default-enabled async_if_stopped cli flag

- pkg/reconciler/app/controller.go
- pkg/reconciler/route/controller.go
These are the two big reconcilers we have which should experience the greatest amount of churn yet should still be relatively safe for increasing, the default number of goroutines  handling is 2. 10 is an arbitrary number but doesn't seem like it's too high.
> Increase concurrency of app and route reconcilers.

- ci/cloudbuild/test.yaml
* Unpins the Gcloud SDK version used for CI/CD test runs
> Unpin GcloudSDK version previously set to 417.0.1 to work around artifact registry bug

- docs/content/en/docs/v2.11/migrating/_index.md
- docs/content/en/docs/v2.11/migrating/builds.md
Added documentation for migrating to external builds via Dockerfile or Pack CLI along with recommendations for teams coming from CF or Kf.
> Added documentation for migrating to external builds.

- config/controller.yaml
- config/webhook.yaml
Customers are seeing throttling with the current setup for the webhook. When these were created they operated on smaller resources (before K8s started copying lots of data into the metadata to track field ownership) so they're both likely due for a refresh.
> Increase memory and CPU for controller/webhook.

- pkg/kf/apps/push.go
- pkg/kf/apps/push_test.go
This step shouldn't actually be necessary and just slows down push because it requires a full extra reconciliation.
> Don't wait for placeholder creation during push.

- docs/content/en/docs/v2.11/cli/generated/kf-xargs-apps.md
- pkg/kf/commands/apps/xargs_apps.go
- pkg/kf/commands/dependencies/dependencies.go
- pkg/kf/commands/root.go
- pkg/kf/internal/genericcli/xargs.go
- pkg/kf/internal/genericcli/xargs_test.go
- pkg/reconciler/garbagecollector/controller.go
- pkg/reconciler/garbagecollector/reconciler.go
* Generated docs for xargs-apps
* Fixed pluralization in xargs-apps
* Fixed incorrect examples in xargs-apps
* Changed xargs-apps into an experimental subcommand
* Added extra comment in xargs-apps to allow exporting as a command
* Fixed garbagecollector logging name
* Added config watcher to garbagecollector logger to prevent a panic
> Fixes for issues in 1.18 pre-release

- docs/config.toml
By default, Docsy truncates lists in the navbar to 50 entries. Kf's CLI uses significantly more. Bumped up the number here to ensure the whole things shows.
> Fixed navigation rendering in CLI docs.

- config/config-defaults.yaml
- docs/content/en/docs/v2.11/operator/customizing/customizing-features.md
- operator/pkg/apis/kfsystem/kf/defaults.go
- pkg/apis/kf/config/defaults.go
- pkg/apis/kf/config/defaults_test.go
- pkg/apis/kf/config/store_test.go
- pkg/reconciler/build/resources/builtin_tasks.go
Tested using an app with 10,000 small files and builds are about 10 seconds faster. For some of the large Java apps we're seeing with 90MB of class files we should see a nice speedup.
* Changed default Kaniko image to v1.15 from v1.0
* Added ability to pick a snapshot mode for v2 buildpacks.
* Changed default snapshot mode from robust to fast for Kaniko when used with v2 builds.
> Use faster kaniko snapshotting.

- pkg/reconciler/featureflag/controller.go
- pkg/reconciler/featureflag/reconciler.go
- pkg/reconciler/featureflag/reconciler_test.go
The Feature Flag reconciler previously was building too long of a queue by enqueueing _all_ namespaces when the config-defaults configmap changed.
While it appears there wasn't any harm due to the reconciler ignoring the keys, it was still leading to concerningly high queue depths and a huge amount of unnecessary work for the controllers.
> Fix feature flag reconciler triggers.

- cmd/build-helpers/extract.go
- pkg/kf/sourcepackages/client.go
- pkg/kf/testutil/acceptance/acceptance_tests.go
- pkg/sourceimage/extract.go
- pkg/sourceimage/extract_test.go
* Added upload time log line to `kf push`.
* Added extracted file count log message to the source extraction build step.
Both of these should make logs more understandable.
> Added observability into build and extraction.

- pkg/reconciler/app/controller.go
These changes should take lower priority than live updates impacting the app itself, like pushes.
This should decrease latency for pushes during cluster changes.
> Enqueue apps on the slow queue when spaces are updated.

- third_party/VENDOR-LICENSE
- third_party/forked/gomod-collector/licenses.go
- third_party/forked/gomod-collector/modules.go
These versions are preventing dependabot from working correctly and with Kf being fully OSS the licenses can be pulled from the source releases.
> Removed versions from vendor license.

- pkg/kf/commands/apps/set_env.go
e.g. `kf set-env FOO` followed by `kf set-env foo` may add both to the environment even though they will be interpreted as the same var by kubernetes.
> fix: set-env may behave incorrectly if variables provided are lowercase

- pkg/reconciler/app/resources/env.go
- pkg/reconciler/app/resources/env_test.go
- pkg/reconciler/app/resources/testdata/golden/testmakesource_buildpack_build.golden
- pkg/reconciler/app/resources/testdata/golden/testmakesource_cascading_env_build.golden
- pkg/reconciler/app/resources/testdata/golden/testmakesource_empty_app_and_space_build.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_empty_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_nfs_volumes_disabled_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_nfs_volumes_enabled_start_command_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_nfs_volumes_enabled_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_timeout_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_unlimited_timeout_taskrun.golden
- pkg/reconciler/task/resources/testdata/golden/testmaketaskrun_unset_timeout_taskrun.golden
* Restore "M" suffix of MEMORY_LIMIT variable value deleted by #1053
```release-note
Fixes: issue with missing "M" suffix in MEMORY_LIMIT variable value
```
> Added "M" suffix to MEMORY_LIMIT environment variable.

- ci/cloudbuild/test.yaml
Ensures that the delete clusters flow executes even when
* cluster turnup succeeds partially (e.g. cluster created but various kubectl apply operations fail)
* other testing stages fail 
This reduces resource waste in our integration testing project.
> chore: ensure that e2e tests cleanup clusters

- pkg/kf/commands/apps/set_env.go
PR: https://github.com/google/kf/pull/1049 is breaking .net Core applications, where lower case environment variables are expected. Proposing this change, before better fix is available
Fixes #
*
*
*
```release-note
```
> Revert PR: https://github.com/google/kf/pull/1049

- cmd/generate-release/scripts/install-asm.bash
- pkg/kf/commands/dependencies/dependencies.go
* Upgraded dependencies - Tekton to 0.53.2, ASM to 1.19 and Config Connector to 1.111
```release-note
CHANGED Server-side dependencies - Tekton to 0.53.2, ASM to 1.19 and Config Connector to 1.111
```
> Upgraded server-side dependencies: Tekton, ASM, Config Connector

- pkg/kf/commands/dependencies/dependencies.go
* Updated Tekton Pipelines dependency to the newest patch for current LTS version - v0.53.3
Changed version of Tekton Pipelines dependency
> Updated Tekton dependency to the newest patch for current LTS version

- pkg/apis/kf/v1alpha1/source_package_validation.go
* Increase size limit for SourcePackage from 1 to 3 GB
Changed size limit for SourcePackage from 1 to 3 GB
> Increased source package size limit to 3 GB

- config/config-defaults.yaml
```release-note
Changed version of php-buildpack used from latest to v4.6.23 as a workaround to github.com/cloudfoundry/php-buildpack/issues/1110
```
> Set version of php-buildpack to v4.6.23 to address git clone error in run-lifecycle task
